ATTACK_TYPE_NORMAL=法術
ATTACK_TYPE_MELEE=普通
ATTACK_TYPE_PIERCE=穿刺
ATTACK_TYPE_SIEGE=攻城
ATTACK_TYPE_MAGIC=魔法
ATTACK_TYPE_CHAOS=混亂
ATTACK_TYPE_HERO=英雄
EFFECT_TYPE_EFFECT=點目標效果
EFFECT_TYPE_TARGET=目標效果
EFFECT_TYPE_CASTER=施法者效果
EFFECT_TYPE_SPECIAL=特殊效果
EFFECT_TYPE_AREA_EFFECT=區域效果
EFFECT_TYPE_MISSILE=投射物效果
EFFECT_TYPE_LIGHTNING=閃電效果
DAMAGE_TYPE_UNKNOWN=未知
DAMAGE_TYPE_NORMAL=法術
DAMAGE_TYPE_ENHANCED=強化
DAMAGE_TYPE_FIRE=火焰
DAMAGE_TYPE_COLD=冰凍DAMAGE_TYPE_COLD=冰凍
DAMAGE_TYPE_LIGHTNING=閃電
DAMAGE_TYPE_POISON=毒藥
DAMAGE_TYPE_DISEASE=疾病
DAMAGE_TYPE_DIVINE=神聖
DAMAGE_TYPE_MAGIC=魔法
DAMAGE_TYPE_SONIC=音速
DAMAGE_TYPE_ACID=酸性
DAMAGE_TYPE_FORCE=力量
DAMAGE_TYPE_DEATH=死亡
DAMAGE_TYPE_MIND=精神
DAMAGE_TYPE_PLANT=植物
DAMAGE_TYPE_DEFENSIVE=防禦
DAMAGE_TYPE_DEMOLITION=破壞
DAMAGE_TYPE_SLOW_POISON=慢性毒藥
DAMAGE_TYPE_SPIRIT_LINK=靈魂鎖鏈
DAMAGE_TYPE_SHADOW_STRIKE=暗影突襲
DAMAGE_TYPE_UNIVERSAL=通用
AI_DIFFICULTY_INSANE=AI難度-令人發瘋的
AI_DIFFICULTY_NEWBIE=AI難度-新手
AI_DIFFICULTY_NORMAL=AI難度-正常
ALLIANCE_HELP_REQUEST=聯盟幫助要求
ALLIANCE_HELP_RESPONSE=聯盟幫助響應
ALLIANCE_PASSIVE=被動聯盟
ALLIANCE_RESCUABLE=聯盟可營救
ALLIANCE_SHARED_CONTROL=聯盟共享控制
ALLIANCE_SHARED_SPELLS=聯盟共享魔法
ALLIANCE_SHARED_VISION=聯盟共享視野
ALLIANCE_SHARED_VISION_FORCED=聯盟勢力共享視野
ALLIANCE_SHARED_XP=聯盟共享優先權
BLEND_MODE_ADDITIVE=合成算法-附加混合
BLEND_MODE_BLEND=合成算法-普通混合
BLEND_MODE_DONT_CARE=合成算法-
BLEND_MODE_KEYALPHA=合成算法-關鍵的alpha混合
BLEND_MODE_MODULATE=合成算法-調整混合
BLEND_MODE_MODULATE_2X=合成算法-調整2x混合
BLEND_MODE_NONE=合成算法-無混合
CAMERA_FIELD_ANGLE_OF_ATTACK=鏡頭區域-攻擊角度
CAMERA_FIELD_FARZ=鏡頭區域-遠端
CAMERA_FIELD_FIELD_OF_VIEW=鏡頭區域-區域觀看
CAMERA_FIELD_ROLL=鏡頭區域-滾動
CAMERA_FIELD_ROTATION=鏡頭區域-旋轉
CAMERA_FIELD_TARGET_DISTANCE=鏡頭區域-距離到目標
CAMERA_FIELD_ZOFFSET=鏡頭區域-高度位移
EVENT_DIALOG_BUTTON_CLICK=事件-對話按鈕點擊
EVENT_DIALOG_CLICK=事件-對話點擊
GAME_STATE_TIME_OF_DAY=遊戲狀態-時間
FOG_OF_WAR_FOGGED=可見效果-戰爭迷霧
FOG_OF_WAR_MASKED=可見效果-黑色迷霧
FOG_OF_WAR_VISIBLE=可見效果-可見
MAP_DIFFICULTY_EASY=地圖難度-容易
MAP_DIFFICULTY_HARD=地圖難度-困難
MAP_DIFFICULTY_INSANE=地圖難度-令人發瘋的
MAP_DIFFICULTY_NORMAL=地圖難度-正常
EVENT_GAME_BUILD_SUBMENU=遊戲事件-創建子菜單
EVENT_GAME_END_LEVEL=遊戲事件-遊戲本關結束
EVENT_GAME_ENTER_REGION=遊戲事件-進入區域
EVENT_GAME_LEAVE_REGION=遊戲事件-離開區域
EVENT_GAME_LOADED=遊戲事件-遊戲裝載完畢
EVENT_GAME_SAVE=遊戲事件-儲存
EVENT_GAME_SHOW_SKILL=遊戲事件-顯示技能
EVENT_GAME_STATE_LIMIT=遊戲事件-遊戲狀態限制
EVENT_GAME_TIMER_EXPIRED=遊戲事件-遊戲超時
EVENT_GAME_TOURNAMENT_FINISH_NOW=遊戲事件-比賽完成
EVENT_GAME_TOURNAMENT_FINISH_SOON=遊戲事件-比賽即將完成
EVENT_GAME_TRACKABLE_HIT=遊戲事件-可跟蹤打擊
EVENT_GAME_TRACKABLE_TRACK=遊戲事件-可跟蹤跟蹤
EVENT_GAME_VARIABLE_LIMIT=遊戲事件-遊戲變量限制
EVENT_GAME_VICTORY=遊戲事件-遊戲勝利
MAP_SPEED_FAST=地圖-較快遊戲速度
MAP_SPEED_FASTEST=地圖-最快遊戲速度
MAP_SPEED_NORMAL=地圖-正常遊戲速度
MAP_SPEED_SLOW=地圖-低遊戲速度
MAP_SPEED_SLOWEST=地圖-最低遊戲速度
GAME_TYPE_BLIZ=遊戲類型-官方地圖
GAME_TYPE_FFA=遊戲類型-自由競賽
GAME_TYPE_FOUR_TEAM_PLAY=遊戲類型-4隊競賽
GAME_TYPE_MELEE=遊戲類型-對戰
GAME_TYPE_ONE_ON_ONE=遊戲類型-1 對 1
GAME_TYPE_THREE_TEAM_PLAY=遊戲類型-3隊競賽
GAME_TYPE_TWO_TEAM_PLAY=遊戲類型-2隊競賽
GAME_TYPE_USE_MAP_SETTINGS=遊戲類型-使用地圖設置
GAME_STATE_DISCONNECTED=遊戲狀態-斷開
GAME_STATE_DIVINE_INTERVENTION=遊戲狀態-干涉
CAMERA_MARGIN_BOTTOM=鏡頭空白-底部
CAMERA_MARGIN_LEFT=鏡頭空白-左邊
CAMERA_MARGIN_RIGHT=鏡頭空白-右邊
CAMERA_MARGIN_TOP=鏡頭空白-頂部
JASS_MAX_ARRAY_SIZE=數組最大域值
PLAYER_NEUTRAL_AGGRESSIVE=中立敵對玩家
PLAYER_NEUTRAL_PASSIVE=中立被動玩家
ITEM_TYPE_ANY=物品類型-任何種類
ITEM_TYPE_ARTIFACT=物品類型-人造物品
ITEM_TYPE_CAMPAIGN=物品類型-戰役
ITEM_TYPE_CHARGED=物品類型-可充
ITEM_TYPE_MISCELLANEOUS=物品類型-混雜
ITEM_TYPE_PERMANENT=物品類型-永久
ITEM_TYPE_POWERUP=物品類型-升級
ITEM_TYPE_PURCHASABLE=物品類型-可購買
ITEM_TYPE_TOME=物品類型-書
ITEM_TYPE_UNKNOWN=物品類型-未定義種類
EQUAL=等於
GREATER_THAN=大於
GREATER_THAN_OR_EQUAL=大於或等於
LESS_THAN=小於
LESS_THAN_OR_EQUAL=小於等於
NOT_EQUAL=不等於
MAP_CONTROL_COMPUTER=地圖控制者-電腦
MAP_CONTROL_CREEP=地圖控制者-野生
MAP_CONTROL_NEUTRAL=地圖控制者-中立
MAP_CONTROL_NONE=地圖控制者-無
MAP_CONTROL_RESCUABLE=地圖控制者-營救
MAP_CONTROL_USER=地圖控制者-用戶
MAP_DENSITY_HEAVY=地圖-高密度
MAP_DENSITY_LIGHT=地圖-小密度
MAP_DENSITY_MEDIUM=地圖-中等密度
MAP_DENSITY_NONE=地圖-無密度
MAP_ALLIANCE_CHANGES_HIDDEN=地圖-隱藏改變聯盟
MAP_CHEATS=地圖-容許作弊碼
MAP_CHEATS_HIDDEN=地圖-隱藏作弊碼
MAP_FIXED_COLORS=地圖-固定顏色
MAP_FOG_ALWAYS_VISIBLE=地圖迷霧-總是可見
MAP_FOG_HIDE_TERRAIN=地圖迷霧-隱藏地形
MAP_FOG_MAP_EXPLORED=地圖迷霧-地圖已探索
MAP_LOCK_ALLIANCE_CHANGES=地圖-鎖定改變聯盟
MAP_LOCK_RANDOM_SEED=地圖-不容許隨機遊戲速度
MAP_LOCK_RESOURCE_TRADING=地圖-鎖定資源交易
MAP_LOCK_SPEED=地圖-鎖定遊戲速度
MAP_OBSERVERS=地圖-允許有觀察者
MAP_OBSERVERS_ON_DEATH=地圖-默認為觀看者
MAP_RANDOM_HERO=地圖-隨機英雄
MAP_RANDOM_RACES=地圖-隨機種族
MAP_RELOADED=地圖-地圖轉換
MAP_RESOURCE_TRADING_ALLIES_ONLY=地圖-容許聯盟資源交易
MAP_SHARED_ADVANCED_CONTROL=地圖-共享高級控制
MAP_USE_HANDICAPS=地圖-使用障礙
MAP_PLACEMENT_FIXED=地圖-玩家固定放置
MAP_PLACEMENT_RANDOM=地圖-玩家隨機放置
MAP_PLACEMENT_TEAMS_TOGETHER=地圖-同一聯盟玩家放置在一起
MAP_PLACEMENT_USE_MAP_SETTINGS=地圖-使用地圖設置的玩家放置
PLAYER_COLOR_AQUA=玩家顏色-淺綠
PLAYER_COLOR_BLUE=玩家顏色-藍
PLAYER_COLOR_BROWN=玩家顏色-棕色
PLAYER_COLOR_CYAN=玩家顏色-青
PLAYER_COLOR_GREEN=玩家顏色-綠
PLAYER_COLOR_LIGHT_BLUE=玩家顏色-亮藍
PLAYER_COLOR_LIGHT_GRAY=玩家顏色-亮灰
PLAYER_COLOR_ORANGE=玩家顏色-橙
PLAYER_COLOR_PINK=玩家顏色-粉紅
PLAYER_COLOR_PURPLE=玩家顏色-紫
PLAYER_COLOR_RED=玩家顏色-紅
PLAYER_COLOR_YELLOW=玩家顏色-黃
EVENT_PLAYER_ALLIANCE_CHANGED=玩家事件-盟友設置變化
EVENT_PLAYER_ARROW_DOWN_DOWN=玩家事件-按下鍵
EVENT_PLAYER_ARROW_DOWN_UP=玩家事件-釋放下鍵
EVENT_PLAYER_ARROW_LEFT_DOWN=玩家事件-按左鍵
EVENT_PLAYER_ARROW_LEFT_UP=玩家事件-釋放左鍵
EVENT_PLAYER_ARROW_RIGHT_DOWN=玩家事件-按右鍵
EVENT_PLAYER_ARROW_RIGHT_UP=玩家事件-釋放右鍵
EVENT_PLAYER_ARROW_UP_DOWN=玩家事件-按上鍵
EVENT_PLAYER_ARROW_UP_UP=玩家事件-釋放上鍵
EVENT_PLAYER_CHAT=玩家事件-聊天
EVENT_PLAYER_DEFEAT=玩家事件-失敗
EVENT_PLAYER_END_CINEMATIC=玩家事件-結束電影
EVENT_PLAYER_LEAVE=玩家事件-離開
EVENT_PLAYER_STATE_LIMIT=玩家事件-狀態限制
EVENT_PLAYER_VICTORY=玩家事件-勝利
PLAYER_GAME_RESULT_DEFEAT=玩家結果-失敗
PLAYER_GAME_RESULT_NEUTRAL=玩家結果-不確定
PLAYER_GAME_RESULT_TIE=玩家結果-平局
PLAYER_GAME_RESULT_VICTORY=玩家結果-勝利
PLAYER_SCORE_FOOD_MAXPROD=玩家積分-最大的人口數量
PLAYER_SCORE_FOOD_MAXUSED=玩家積分-最大所使用的人口數量
PLAYER_SCORE_GOLD_GIVEN=玩家積分-給予盟友的金子
PLAYER_SCORE_GOLD_LOST_TAX=玩家積分-由於稅而損失的金子
PLAYER_SCORE_GOLD_LOST_UPKEEP=玩家積分-因為維修費而損失的金
PLAYER_SCORE_GOLD_MINED_TOTAL=玩家積分-所採集的金子 (總共)
PLAYER_SCORE_GOLD_MINED_UPKEEP=玩家積分-所採集的金子(帶有維修
PLAYER_SCORE_GOLD_RECEIVED=玩家積分-從盟友那裡收到的金子
PLAYER_SCORE_HERO_TOTAL=玩家積分-總的英雄得分
PLAYER_SCORE_HEROES_KILLED=玩家積分-殺死英雄
PLAYER_SCORE_ITEMS_GAINED=玩家積分-獲得物品
PLAYER_SCORE_LUMBER_GIVEN=玩家積分-給予盟友的木材
PLAYER_SCORE_LUMBER_LOST_TAX=玩家積分-由於稅而損失的木材
PLAYER_SCORE_LUMBER_LOST_UPKEEP=玩家積分-由於維修費而損失的木
PLAYER_SCORE_LUMBER_RECEIVED=玩家積分-從盟友那裡收到的木材
PLAYER_SCORE_LUMBER_TOTAL=玩家積分-採集到的木材
PLAYER_SCORE_MERCS_HIRED=玩家積分-雇傭兵
PLAYER_SCORE_RESOURCE_TOTAL=玩家積分-總的資源得分
PLAYER_SCORE_STRUCT_BUILT=玩家積分-已建造建築
PLAYER_SCORE_STRUCT_RAZED=玩家積分-被毀建築
PLAYER_SCORE_TECH_PERCENT=玩家積分-科技百分比
PLAYER_SCORE_TOTAL=玩家積分-總的整體得分
PLAYER_SCORE_UNIT_TOTAL=玩家積分-總的單位得分
PLAYER_SCORE_UNITS_KILLED=玩家積分-消滅單位
PLAYER_SCORE_UNITS_TRAINED=玩家積分-已訓練單位
PLAYER_SLOT_STATE_EMPTY=空的玩家槽
PLAYER_SLOT_STATE_LEFT=玩家離開的玩家槽
PLAYER_SLOT_STATE_PLAYING=正在使用的玩家槽
PLAYER_STATE_ALLIED_VICTORY=玩家狀態-聯盟勝利
PLAYER_STATE_FOOD_CAP_CEILING=玩家狀態-食物最大容量
PLAYER_STATE_GAME_RESULT=玩家狀態-遊戲結果
PLAYER_STATE_GIVES_BOUNTY=玩家狀態-給予獎勵
PLAYER_STATE_GOLD_GATHERED=玩家狀態-已收集金錢
PLAYER_STATE_GOLD_UPKEEP_RATE=玩家狀態-金錢維護率
PLAYER_STATE_LUMBER_GATHERED=玩家狀態-已收集木材
PLAYER_STATE_LUMBER_UPKEEP_RATE=玩家狀態-木材維護率
PLAYER_STATE_NO_CREEP_SLEEP=玩家狀態-野生生物不睡眠
PLAYER_STATE_OBSERVER=玩家狀態-觀看者
PLAYER_STATE_OBSERVER_ON_DEATH=玩家狀態-默認為觀看者
PLAYER_STATE_PLACED=玩家狀態-放置
PLAYER_STATE_RESOURCE_FOOD_CAP=玩家狀態-食物容量
PLAYER_STATE_RESOURCE_FOOD_USED=玩家狀態-食物使用
PLAYER_STATE_RESOURCE_GOLD=玩家狀態-金錢資源
PLAYER_STATE_RESOURCE_HERO_TOKENS=玩家狀態-使用英雄
PLAYER_STATE_RESOURCE_LUMBER=玩家狀態-木材資源
PLAYER_STATE_UNFOLLOWABLE=玩家狀態-不可跟隨
EVENT_PLAYER_HERO_LEVEL=玩家英雄事件-提升一個等級
EVENT_PLAYER_HERO_REVIVABLE=玩家英雄事件-變得可重生的
EVENT_PLAYER_HERO_REVIVE_CANCEL=玩家英雄事件-取消重生
EVENT_PLAYER_HERO_REVIVE_FINISH=玩家英雄事件-完成重生
EVENT_PLAYER_HERO_REVIVE_START=玩家英雄事件-開始重生
EVENT_PLAYER_HERO_SKILL=玩家英雄事件-學習一項技能
EVENT_PLAYER_UNIT_ATTACKED=玩家單位事件-被攻擊的
EVENT_PLAYER_UNIT_CHANGE_OWNER=玩家單位事件-變化擁有者
EVENT_PLAYER_UNIT_CONSTRUCT_CANCEL=玩家單位事件-取消建造
EVENT_PLAYER_UNIT_CONSTRUCT_FINISH=玩家單位事件-完成建造
EVENT_PLAYER_UNIT_CONSTRUCT_START=玩家單位事件-開始建造
EVENT_PLAYER_UNIT_DEATH=玩家單位事件-死亡
EVENT_PLAYER_UNIT_DECAY=玩家單位事件-衰退
EVENT_PLAYER_UNIT_DESELECTED=玩家單位事件-取消選擇
EVENT_PLAYER_UNIT_DETECTED=玩家單位事件-被發現
EVENT_PLAYER_UNIT_DROP_ITEM=玩家單位事件-丟失一件物品
EVENT_PLAYER_UNIT_HIDDEN=玩家單位事件-隱藏
EVENT_PLAYER_UNIT_ISSUED_ORDER=玩家單位事件-發布一個無目標的
EVENT_PLAYER_UNIT_ISSUED_POINT_ORDER=玩家單位事件-發布一個鎖定一個
EVENT_PLAYER_UNIT_ISSUED_TARGET_ORDER=玩家單位事件-發布一個目標指令
EVENT_PLAYER_UNIT_ISSUED_UNIT_ORDER=玩家單位事件-發布一個鎖定一個
EVENT_PLAYER_UNIT_LOADED=玩家單位事件-裝進了傳送門
EVENT_PLAYER_UNIT_PAWN_ITEM=玩家單位事件-抵押物品(到商店)
EVENT_PLAYER_UNIT_PICKUP_ITEM=玩家單位事件-獲得一件物品
EVENT_PLAYER_UNIT_RESCUED=玩家單位事件-被營救了
EVENT_PLAYER_UNIT_RESEARCH_CANCEL=玩家單位事件-取消研究
EVENT_PLAYER_UNIT_RESEARCH_FINISH=玩家單位事件-完成研究
EVENT_PLAYER_UNIT_RESEARCH_START=玩家單位事件-開始研究
EVENT_PLAYER_UNIT_SELECTED=玩家單位事件-被選擇
EVENT_PLAYER_UNIT_SELL=玩家單位事件-販賣一個單位
EVENT_PLAYER_UNIT_SELL_ITEM=玩家單位事件-購買物品(從商店)
EVENT_PLAYER_UNIT_SPELL_CAST=玩家單位事件-開始施放一種技能
EVENT_PLAYER_UNIT_SPELL_CHANNEL=玩家單位事件-開始一種持續性技
EVENT_PLAYER_UNIT_SPELL_EFFECT=玩家單位事件-開始一種技能的效
EVENT_PLAYER_UNIT_SPELL_ENDCAST=玩家單位事件-停止施放一種技能
EVENT_PLAYER_UNIT_SPELL_FINISH=玩家單位事件-施放技能結束
EVENT_PLAYER_UNIT_SUMMON=玩家單位事件-產生一個召喚單位
EVENT_PLAYER_UNIT_TRAIN_CANCEL=玩家單位事件-取消訓練一個單位
EVENT_PLAYER_UNIT_TRAIN_FINISH=玩家單位事件-完成訓練一個單位
EVENT_PLAYER_UNIT_TRAIN_START=玩家單位事件-開始訓練一個單位
EVENT_PLAYER_UNIT_UPGRADE_CANCEL=玩家單位事件-取消升級
EVENT_PLAYER_UNIT_UPGRADE_FINISH=玩家單位事件-完成升級
EVENT_PLAYER_UNIT_UPGRADE_START=玩家單位事件-開始升級
EVENT_PLAYER_UNIT_USE_ITEM=玩家單位事件-使用一件物品
RACE_DEMON=惡魔族
RACE_HUMAN=人族
RACE_NIGHTELF=暗夜精靈族
RACE_ORC=獸族
RACE_OTHER=特殊
RACE_PREF_DEMON=惡魔族
RACE_PREF_HUMAN=人族
RACE_PREF_NIGHTELF=暗夜精靈族
RACE_PREF_ORC=獸族
RACE_PREF_UNDEAD=不死族
RARITY_FREQUENT=頻率控制-普通頻率
RARITY_RARE=頻率控制-罕見的
MAP_LOC_PRIO_HIGH=起始位置分布優先權-高
MAP_LOC_PRIO_LOW=起始位置分布優先權-低
MAP_LOC_PRIO_NOT=起始位置分布優先權-無
TEXMAP_FLAG_NONE=地圖塗層標誌-無
TEXMAP_FLAG_WRAP_U=地圖塗層標誌-重疊(U)
TEXMAP_FLAG_WRAP_UV=地圖塗層標誌-重疊(UV)
TEXMAP_FLAG_WRAP_V=地圖塗層標誌-重疊(V)
EVENT_UNIT_ACQUIRED_TARGET=單位事件-獲得一個目標
EVENT_UNIT_ATTACKED=單位事件-被攻擊
EVENT_UNIT_CHANGE_OWNER=單位事件-變化擁有者
EVENT_UNIT_CONSTRUCT_CANCEL=單位事件-取消建造
EVENT_UNIT_CONSTRUCT_FINISH=單位事件-完成建造
EVENT_UNIT_DAMAGED=單位事件-接受傷害
EVENT_UNIT_DEATH=單位事件-死亡
EVENT_UNIT_DECAY=單位事件-衰退
EVENT_UNIT_DESELECTED=單位事件-取消選擇
EVENT_UNIT_DETECTED=單位事件-被發現
EVENT_UNIT_DROP_ITEM=單位事件-丟失一件物品
EVENT_UNIT_HERO_LEVEL=英雄單位事件-提升一個等級
EVENT_UNIT_HERO_REVIVABLE=英雄單位事件-變得可重生的
EVENT_UNIT_HERO_REVIVE_CANCEL=英雄單位事件-取消重生
EVENT_UNIT_HERO_REVIVE_FINISH=英雄單位事件-完成重生
EVENT_UNIT_HERO_REVIVE_START=英雄單位事件-開始重生
EVENT_UNIT_HERO_SKILL=英雄單位事件-學習一項技能
EVENT_UNIT_HIDDEN=單位事件-隱藏
EVENT_UNIT_ISSUED_ORDER=單位事件-發布一個無目標的指令
EVENT_UNIT_ISSUED_POINT_ORDER=單位事件-發布一個鎖定一個點的
EVENT_UNIT_ISSUED_TARGET_ORDER=單位事件-發布一個鎖定目標的指
EVENT_UNIT_LOADED=單位事件-裝進了傳送門
EVENT_UNIT_PAWN_ITEM=單位事件-抵押物品(到商店)
EVENT_UNIT_PICKUP_ITEM=單位事件-獲得一件物品
EVENT_UNIT_RESCUED=單位事件-被營救
EVENT_UNIT_RESEARCH_CANCEL=單位事件-取消研究
EVENT_UNIT_RESEARCH_FINISH=單位事件-完成研究
EVENT_UNIT_RESEARCH_START=單位事件-開始研究
EVENT_UNIT_SELECTED=單位事件-被選擇
EVENT_UNIT_SELL=單位事件-販賣一個單位
EVENT_UNIT_SELL_ITEM=單位事件-購買物品(從商店)
EVENT_UNIT_SPELL_CAST=單位事件-開始施放一種技能
EVENT_UNIT_SPELL_CHANNEL=單位事件-開始一種持續性技能
EVENT_UNIT_SPELL_EFFECT=單位事件-開始一種技能的效果
EVENT_UNIT_SPELL_ENDCAST=單位事件-停止施放一種技能
EVENT_UNIT_SPELL_FINISH=單位事件-施放技能結束
EVENT_UNIT_STATE_LIMIT=單位事件-狀態限制
EVENT_UNIT_SUMMON=單位事件-產生一個召喚單位
EVENT_UNIT_TARGET_IN_RANGE=單位事件-注意範圍內的一個目標
EVENT_UNIT_TRAIN_CANCEL=單位事件-取消訓練一個單位
EVENT_UNIT_TRAIN_FINISH=單位事件-完成訓練一個單位
EVENT_UNIT_TRAIN_START=單位事件-開始訓練一個單位
EVENT_UNIT_UPGRADE_CANCEL=單位事件-取消升級
EVENT_UNIT_UPGRADE_FINISH=單位事件-完成升級
EVENT_UNIT_UPGRADE_START=單位事件-開始升級
EVENT_UNIT_USE_ITEM=單位事件-使用一件物品
UNIT_STATE_LIFE=單位狀態-生命
UNIT_STATE_MANA=單位狀態-法力
UNIT_STATE_MAX_LIFE=單位狀態-最大生命
UNIT_STATE_MAX_MANA=單位狀態-最大法力
UNIT_TYPE_ANCIENT=單位類型-古代的
UNIT_TYPE_ATTACKS_FLYING=單位類型-可以攻擊飛行單位
UNIT_TYPE_ATTACKS_GROUND=單位類型-可以攻擊地 單位
UNIT_TYPE_DEAD=單位類型-死亡單位
UNIT_TYPE_FLYING=單位類型-飛行單位
UNIT_TYPE_GIANT=單位類型-巨人
UNIT_TYPE_GROUND=單位類型-地面單位
UNIT_TYPE_HERO=單位類型-英雄
UNIT_TYPE_MECHANICAL=單位類型-機械的
UNIT_TYPE_MELEE_ATTACKER=單位類型-肉搏攻擊者
UNIT_TYPE_PEON=單位類型-苦工
UNIT_TYPE_PLAGUED=單位類型-中了瘟疫的
UNIT_TYPE_RANGED_ATTACKER=單位類型-遠程攻擊者
UNIT_TYPE_SAPPER=單位類型-工兵
UNIT_TYPE_SNARED=單位類型-被誘捕的
UNIT_TYPE_STRUCTURE=單位類型-建築單位
UNIT_TYPE_STUNNED=單位類型-被暈眩的
UNIT_TYPE_SUMMONED=單位類型-被召喚的
UNIT_TYPE_TOWNHALL=單位類型-城鎮大廳類型單位
UNIT_TYPE_UNDEAD=單位類型-不死的
VERSION_FROZEN_THRONE=版本-冰封王座
VERSION_REIGN_OF_CHAOS=版本-混亂之治
SOUND_VOLUMEGROUP_AMBIENTSOUNDS=場景配音
SOUND_VOLUMEGROUP_COMBAT=戰鬥聲音
SOUND_VOLUMEGROUP_FIRE=火焰聲音
SOUND_VOLUMEGROUP_MUSIC=音樂
SOUND_VOLUMEGROUP_SPELLS=動畫和法術聲音
SOUND_VOLUMEGROUP_UI=用戶界面聲音
SOUND_VOLUMEGROUP_UNITMOVEMENT=單位移動聲音
SOUND_VOLUMEGROUP_UNITSOUNDS=單位回應聲音
EVENT_WIDGET_DEATH=事件-容器死亡
bj_E=e
bj_PI=π
bj_TEXT_DELAY_SECRET=戰役秘密等待
bj_CELLWIDTH=單元點寬度
bj_UNIT_FACING=默認建築朝向
bj_TEXT_DELAY_HINT=戰役提示等待
bj_TEXT_DELAY_QUEST=戰役任務等待
----------此條功能(=判斷常量專用，請不要修改此行否則可能會出錯----------(
local =局部變量
constant =常量
 array = 數組
unit =單位
string =字符串
ability =技能
boolean =布爾值
camerasetup =鏡頭
destructable =可破壞物
defeatcondition =失敗條件
timer =計時器
timerdialog =計時器窗口
dialog =對話框
button =對話框按鈕
texttag =漂浮文字
gamecache =遊戲緩存
gamespeed =遊戲速度
integer =整數
item =物品
itemtype =物品分類
leaderboard =排行榜
multiboard =多面板
player =玩家
widget =容器
playercolor =玩家顏色
force =玩家組
location =點
quest =任務
questitem =任務項目
race =種族
real =實數
sound =聲音
weathereffect =天氣效果
effect =特效
trigger =觸發器
group =單位組
fogmodifier =可見度修正器
terraindeformation =地形變化
event =觸發事件
triggercondition =觸發條件
triggeraction =觸發動作
boolexpr =布爾表達式
unittype =單位分類
alliancetype =聯盟類型
playerstate =玩家屬性
playerscore =玩家得分
playergameresult =玩家得分
unitstate =單位屬性
playerunitevent =玩家單位事件
limitop =比較符
gamedifficulty =遊戲難度
gameevent =遊戲事件
aidifficulty =對戰AI
mapdensity =密集度
mapcontrol =玩家控制者
mapflag =地圖參數
playerslotstate =玩家遊戲狀態
camerafield =鏡頭屬性
raritycontrol =動畫類型
blendmode =混合方式
fogstate =可見狀態
volumegroup =聲音通道
rect =矩形區域
lightning =閃電效果
I2S(=轉換整數為字符串(
R2S(=轉換實數為字符串(
R2SW(=格式轉換實數為字符串(
ConvertPlayerColor(=玩家顏色(
TriggerRegisterGameLoadedEventBJ(=讀取進度(
TriggerRegisterGameSavedEventBJ(=保存進度(
TriggerRegisterShowSkillEventBJ(=學習技能按鈕被點擊(
TriggerRegisterBuildSubmenuEventBJ(=建造按鈕被點擊(
TriggerRegisterTimerExpireEventBJ(=計時器到期(
TriggerRegisterDialogEventBJ(=對話框點擊(
TriggerRegisterPlayerSelectionEventBJ(=選擇事件(
TriggerRegisterPlayerKeyEventBJ(=鍵盤事件(
TriggerRegisterAnyUnitEventBJ(=任意單位事件(
WaitForSoundBJ(=等待音效(
TriggerExecuteBJ(=運行觸發(檢查條件)(
QueuedTriggerAddBJ(=添加到觸發隊列(
QueuedTriggerRemoveBJ(=移出觸發隊列(
QueuedTriggerClearBJ(=清空觸發隊列(
QueuedTriggerClearInactiveBJ(=清空未運行觸發(
CreateNUnitsAtLocFacingLocBJ(=創建單位(面向點)(
CreateCorpseLocBJ(=創建屍體(
CreatePermanentCorpseLocBJ(=創建永久性屍體(
ExplodeUnitBJ(=爆炸(
ReplaceUnitBJ(=替換(
UnitShareVisionBJ(=共享視野 [R](
SetUnitPositionLocFacingLocBJ(=移動單位面向點(立即)(
SetUnitPositionLocFacingBJ(=移動單位面向角度(立即)(
SetUnitLifePercentBJ(=設置生命值(百分比)(
SetUnitManaPercentBJ(=設置魔法值(百分比)(
SetUnitLifeBJ(=設置生命值(指定值)(
SetUnitManaBJ(=設置魔法值(指定值)(
PauseUnitBJ(=暫停/恢復 [R](
PauseAllUnitsBJ(=暫停/恢復所有單位(
UnitPauseTimedLifeBJ(=暫停/恢復生命週期 [R](
UnitApplyTimedLifeBJ(=設置生命週期 [R](
SetUnitExplodedBJ(=設置死亡方式(
UnitSuspendDecayBJ(=暫停屍體腐爛 [R](
UnitSetCanSleepBJ(=設置單位夜晚睡眠(
UnitWakeUpBJ(=叫醒單位(
RescueUnitBJ(=營救單位(
MakeUnitRescuableToForceBJ(=設置可否營救(對玩家組)(
SetRescueUnitColorChangeBJ(=設置營救顏色(單位)(
SetRescueBuildingColorChangeBJ(=設置營救顏色(建築)(
SetUnitUseFoodBJ(=允許/禁止人口占用 [R](
SetUnitAcquireRangeBJ(=設置主動攻擊範圍(
UnitRemoveBuffsExBJ(=刪除魔法傚果(詳細類別) [R](
UnitRemoveBuffsBJ(=刪除魔法傚果(指定極性) [R](
UnitRemoveBuffBJ(=刪除指定魔法傚果(
UnitAddAbilityBJ(=添加技能 [R](
UnitRemoveAbilityBJ(=刪除技能 [R](
UnitMakeAbilityPermanentBJ(=設置技能永久性 [R](
UnitAddTypeBJ(=添加類別 [R](
UnitRemoveTypeBJ(=刪除類別 [R](
IssueImmediateOrderBJ(=發布命令(無目標)(
IssuePointOrderLocBJ(=發布命令(指定點)(
IssueTargetOrderBJ(=發布命令(指定單位)(
IssueTrainOrderByIdBJ(=發布訓練/升級命令(
IssueUpgradeOrderByIdBJ(=發布研究科技命令(
IssueBuildOrderByIdLocBJ(=發布建造命令(指定點)(
UnitDropItemPointBJ(=發布丟棄物品命令(指定坐標) [R](
UnitDropItemSlotBJ(=移動物品到物品欄 [R](
UnitDropItemTargetBJ(=發布給予物品命令(
UnitDamageTargetBJ(=傷害目標 [R](
ForGroupBJ(=選取單位組內單位做動作(
GroupImmediateOrderBJ(=發布命令(無目標)(
GroupPointOrderLocBJ(=發布命令(指定點)(
GroupTargetOrderBJ(=發布命令(指定單位)(
GroupTrainOrderByIdBJ(=發布發布訓練/升級命令(
CreateUbersplatBJ(=創建(
ShowUbersplatBJ(=顯示/隱藏 [R](
TransmissionFromUnitWithNameBJ(=播送單位消息(指定單位)(
TransmissionFromUnitTypeWithNameBJ(=播送單位消息(指定單位類型)(
ForceCinematicSubtitlesBJ(=字幕顯示(
CinematicModeExBJ(=電影模式(指定時間)(
CinematicModeBJ(=電影模式(
CinematicFadeBJ(=淡入淡出濾鏡(
CinematicFilterGenericBJ(=高級濾鏡(
DisplayCineFilterBJ(=顯示/隱藏濾鏡(
UnitAddIndicatorBJ(=閃動指示器(對單位) [R](
DestructableAddIndicatorBJ(=閃動指示器(對可破壞物) [R](
ItemAddIndicatorBJ(=閃動指示器(對物品) [R](
EnableOcclusionBJ(=允許/禁止閉塞(所有玩家) [R](
EnableWorldFogBoundaryBJ(=允許/禁止邊界染色(所有玩家) [R](
QueueUnitAnimationBJ(=將單位動畫加入隊列(
AddUnitAnimationPropertiesBJ(=添加/刪除單位動畫附加名 [R](
SetUnitVertexColorBJ(=改變單位顏色 [R](
SetUnitTurnSpeedBJ(=改變單位轉身速度(
SetUnitBlendTimeBJ(=改變單位混合時間(
SetUnitFlyHeightBJ(=改變單位飛行高度(
SetUnitPropWindowBJ(=改變單位轉向角度(弧度制) [R](
SetDestructableAnimationBJ(=播放可破壞物動畫(
QueueDestructableAnimationBJ(=將可破壞物動畫加入隊列(
SetDoodadAnimationRectBJ(=播放矩形區域內地形裝飾物動畫 [R](
SetDoodadAnimationBJ(=播放圓範圍內地形裝飾物動畫 [R](
DialogDisplayBJ(=顯示/隱藏 [R](
DialogSetMessageBJ(=設置標題(
DialogAddButtonWithHotkeyBJ(=添加對話框按鈕(有快捷鍵) [R](
DialogAddButtonBJ(=添加對話框按鈕(
DialogClearBJ(=清空對話框(
CreateMultiboardBJ(=創建(
DestroyMultiboardBJ(=刪除(
MultiboardDisplayBJ(=顯示/隱藏 [R](
MultiboardAllowDisplayBJ(=顯示/隱藏多面板模式(
MultiboardMinimizeBJ(=最大/最小化 [R](
MultiboardSetTitleTextColorBJ(=設置標題顏色 [R](
MultiboardSetItemStyleBJ(=設置指定項目顯示風格 [R](
MultiboardSetItemValueBJ(=設置指定項目文本 [R](
MultiboardSetItemWidthBJ(=設置指定項目寬度 [R](
MultiboardSetItemIconBJ(=設置指定項目圖標 [R](
MultiboardSetItemColorBJ(=設置項目顏色 [舊](
RemoveWeatherEffectBJ(=刪除天氣效果(
TerrainDeformationCraterBJ(=創建地形變化:彈坑(
TerrainDeformationRippleBJ(=創建地形變化:波紋(
TerrainDeformationWaveBJ(=創建地形變化:衝擊波(
TerrainDeformationRandomBJ(=創建地形變化:隨機(
TerrainDeformationStopBJ(=停止地形變化(
SetTerrainTypeBJ(=改變地形類型(指定坐標) [R](
SetTerrainPathableBJ(=設置地形通行狀態(指定坐標) [R](
SetWaterBaseColorBJ(=設置水顏色 [R](
SetTerrainFogExBJ(=設置迷霧 [R](
ResetTerrainFogBJ(=重置迷霧(
SetBlightRectBJ(=創建/刪除荒蕪地表(矩形區域) [R](
SetBlightRadiusLocBJ(=創建/刪除荒蕪地表(圓範圍)(指定點)(
StartTimerBJ(=開啟計時器(
PauseTimerBJ(=暫停計時器 [R](
DestroyTimerBJ(=刪除計時器 [R](
CreateTimerDialogBJ(=創建計時器窗口(
DestroyTimerDialogBJ(=刪除計時器窗口(
TimerDialogDisplayBJ(=顯示/隱藏計時器窗口(所有玩家) [R](
TimerDialogDisplayForPlayerBJ(=顯示/隱藏計時器窗口(指定玩家)(
TimerDialogSetTitleBJ(=改變計時器窗口標題(
TimerDialogSetTitleColorBJ(=改變計時器窗口文字顏色 [R](
TimerDialogSetTimeColorBJ(=改變計時器窗口時間顏色 [R](
TimerDialogSetSpeedBJ(=設置計時器窗口速率 [R](
SmartCameraPanBJ(=在必要時平移鏡頭(指定玩家)(
RotateCameraAroundLocBJ(=指定點旋轉鏡頭(指定玩家)(
SetCameraOrientControllerForPlayerBJ(=鎖定鏡頭到單位(固定鏡頭源)(指定玩家)(
StopCameraForPlayerBJ(=停止播放鏡頭(指定玩家)(
CameraSetSmoothingFactorBJ(=設置鏡頭平滑參數(
CameraResetSmoothingFactorBJ(=重置鏡頭平滑參數(
AdjustCameraBoundsForPlayerBJ(=擴張/收縮可用鏡頭區域(指定玩家)(
SetCameraBoundsToRectForPlayerBJ(=設置可用鏡頭區域(指定玩家)(
CreateFogModifierRectBJ(=創建可見度修正器(矩形區域)(
CreateFogModifierRadiusLocBJ(=創建可見度修正器(圓範圍)(
CreateDeadDestructableLocBJ(=創建可破壞物(死亡)(
ShowDestructableBJ(=顯示/隱藏 [R](
SetDestructableLifePercentBJ(=設置生命值(百分比)(
SetDestructableMaxLifeBJ(=設置最大生命值(
ModifyGateBJ(=打開/關閉/破壞大門(
SetDestructableInvulnerableBJ(=設置無敵/可攻擊(
EnumDestructablesInCircleBJ(=選取指定點範圍內可破壞物做動作(
CreateLeaderboardBJ(=創建(
DestroyLeaderboardBJ(=刪除(
LeaderboardSortItemsBJ(=排序(
LeaderboardDisplayBJ(=顯示/隱藏 [R](
LeaderboardSetLabelBJ(=設置標題(
LeaderboardSetLabelColorBJ(=設置文字顏色 [R](
LeaderboardSetValueColorBJ(=設置數值顏色 [R](
LeaderboardSetStyleBJ(=設置顯示樣式(
LeaderboardAddItemBJ(=添加玩家(
LeaderboardRemovePlayerItemBJ(=移除玩家(
LeaderboardSetPlayerItemLabelBJ(=改變玩家名字(
LeaderboardSetPlayerItemLabelColorBJ(=改變玩家名字顏色(
LeaderboardSetPlayerItemValueBJ(=改變玩家分數(
LeaderboardSetPlayerItemValueColorBJ(=改變玩家分數顏色(
LeaderboardSetPlayerItemStyleBJ(=設置玩家顯示樣式(
CreateTextTagLocBJ(=創建漂浮文字(指定點)(
CreateTextTagUnitBJ(=創建漂浮文字(指定單位)(
DestroyTextTagBJ(=刪除(
ShowTextTagForceBJ(=顯示/隱藏(指定玩家組)(
SetTextTagVelocityBJ(=設置速率 [R](
SetTextTagColorBJ(=改變顏色 [R](
SetTextTagPosBJ(=改變位置(指定坐標) [R](
SetTextTagPosUnitBJ(=改變位置(指定單位)(
SetTextTagTextBJ(=改變文字 [R](
SetTextTagSuspendedBJ(=暫停/恢復(
SetTextTagPermanentBJ(=設置永久性(
SetTextTagLifespanBJ(=設置生命週期(
SetTextTagFadepointBJ(=設置消逝時間點(
SetTextTagAgeBJ(=設置已存在時間(
QuestMessageBJ(=發送任務信息(
CreateQuestBJ(=創建任務(
DestroyQuestBJ(=刪除任務(
QuestSetEnabledBJ(=啟用/禁用任務 [R](
QuestSetCompletedBJ(=設置任務完成(
QuestSetFailedBJ(=設置任務失敗(
QuestSetDiscoveredBJ(=設置任務被發現(
QuestSetTitleBJ(=設置任務標題(
QuestSetDescriptionBJ(=設置任務說明(
CreateQuestItemBJ(=創建任務項目(
QuestItemSetCompletedBJ(=設置任務項目完成(
QuestItemSetDescriptionBJ(=改變任務項目說明(
CreateDefeatConditionBJ(=創建失敗條件(
DestroyDefeatConditionBJ(=刪除失敗條件(
DefeatConditionSetDescriptionBJ(=改變失敗條件說明(
FlashQuestDialogButtonBJ(=閃動任務按鈕(
DestroyLightningBJ(=刪除(
SetLightningColorBJ(=改變顏色(
PlaySoundBJ(=播放音效(
PlaySoundAtPointBJ(=播放3D音效(指定點)(
PlaySoundOnUnitBJ(=播放3D音效(跟隨單位)(
PlaySoundFromOffsetBJ(=跳播音效(
StopSoundBJ(=停止音效(
KillSoundWhenDoneBJ(=刪除音效(
SetSoundVolumeBJ(=設置音效音量 [R](
SetSoundOffsetBJ(=設置音效播放時間點(
SetSoundDistanceCutoffBJ(=設置聲音截斷距離(
SetSoundPitchBJ(=設置聲音速率(
AttachSoundToUnitBJ(=綁定單位(
SetSoundPositionLocBJ(=設置3D音效位置(指定點)(
SetStackedSoundBJ(=添加/刪除區域音效(
SetMapMusicIndexedBJ(=設置背景音樂列表(指定播放)(
SetMapMusicRandomBJ(=設置背景音樂列表(隨機播放)(
ClearMapMusicBJ(=清空背景音樂列表(
PlayMusicBJ(=播放背景音樂(
PlayMusicExBJ(=跳播背景音樂(
StopMusicBJ(=停止背景音樂(
ResumeMusicBJ(=恢復背景音樂(
SetMusicVolumeBJ(=設置背景音樂音量 [R](
SetMusicOffsetBJ(=設置背景音樂播放時間點(
PlayThematicMusicBJ(=播放主題音樂(
PlayThematicMusicExBJ(=跳播主題音樂 [R](
EndThematicMusicBJ(=停止主題音樂(
SetThematicMusicOffsetBJ(=設置主題音樂播放時間點(
VolumeGroupSetVolumeBJ(=設置多通道音量 [R](
SetCineModeVolumeGroupsBJ(=設置電影多通道音量環境(
SetSpeechVolumeGroupsBJ(=設置語音多通道音量環境(
VolumeGroupResetBJ(=重置多通道音量(
AddSpecialEffectLocBJ(=創建特效(指定點)(
AddSpecialEffectTargetUnitBJ(=創建特效(綁定單位)(
DestroyEffectBJ(=刪除特效(
CreateImageBJ(=創建(
ShowImageBJ(=顯示/隱藏 [R](
SetImagePositionBJ(=改變位置(指定坐標) [R](
SetImageColorBJ(=改變顏色 [R](
SetPlayerStateBJ(=設置屬性(
AdjustPlayerStateBJ(=增加屬性(
SetPlayerFlagBJ(=開啟/關閉玩家參數 [R](
SetPlayerTaxRateBJ(=設置所得稅 [R](
EnableCreepSleepBJ(=允許/禁止中立生物睡眠(
SetPlayerAllianceStateBJ(=設置聯盟狀態(
SetPlayerAllianceBJ(=設置聯盟狀態(指定項目) [R](
SetPlayerAbilityAvailableBJ(=允許/禁用技能 [R](
SetPlayerUnitAvailableBJ(=設置單位可用性(
SetPlayerColorBJ(=改變玩家顏色 [R](
SetPlayerHandicapBJ(=設置生命障礙 [R](
SetPlayerOnScoreScreenBJ(=顯示/隱藏計分屏顯示 [R](
SetForceAllianceStateBJ(=設置聯盟(
SetItemVisibleBJ(=顯示/隱藏 [R](
SetItemLifeBJ(=設置生命值(
SetItemInvulnerableBJ(=設置無敵/可攻擊(
SetItemDroppableBJ(=設置可否丟棄(
SetItemDropOnDeathBJ(=設置死亡是否掉落(
SetItemPlayerBJ(=改變所屬玩家(
EnumItemsInRectBJ(=選取矩形區域內物品做動作(
SelectGroupForPlayerBJ(=選擇單位組(指定玩家)(
SelectGroupBJ(=選擇單位組(所有玩家)(
SetHeroLevelBJ(=設置等級(
SuspendHeroXPBJ(=允許/禁止經驗獲取 [R](
SetPlayerHandicapXPBJ(=設置經驗獲得率 [R](
ClearTextMessagesBJ(=清空文本信息(所有玩家) [R](
LockGameSpeedBJ(=鎖定遊戲速度(
UnlockGameSpeedBJ(=解除鎖定遊戲速度(
SetTimeOfDayScalePercentBJ(=設置晝夜時間流逝速度(
UseTimeOfDayBJ(=開啟/關閉晝夜交替(
CustomVictoryBJ(=勝利(
CustomDefeatBJ(=失敗(
SetNextLevelBJ(=設置下一關卡(
LoadGameBJ(=讀取進度(
SaveAndLoadGameBJ(=保存並讀取進度 [舊](
SaveAndChangeLevelBJ(=保存並切換關卡 [舊](
RenameSaveDirectoryBJ(=重命名存檔文件夾(
RemoveSaveDirectoryBJ(=刪除存檔文件夾(
CopySaveGameBJ(=複製存檔文件(
SetCampaignMenuRaceBJ(=設置戰役背景(
SetMissionAvailableBJ(=允許/禁止關卡(
SetCampaignAvailableBJ(=允許/禁止戰役(
SetCinematicAvailableBJ(=允許/禁止過場電影(
ForceUIKeyBJ(=按下UI鍵(
ForceUICancelBJ(=按下Esc鍵(
EndGameBJ(=結束遊戲 [新](
InitGameCacheBJ(=創建緩存(
SaveGameCacheBJ(=本地保存遊戲緩存(
StoreUnitBJ(=記錄單位(
StoreRealBJ(=記錄實數(
StoreIntegerBJ(=記錄整數(
StoreBooleanBJ(=記錄布爾值(
StoreStringBJ(=記錄字符串(
RestoreUnitLocFacingAngleBJ(=讀取單位(面向角度)(
RestoreUnitLocFacingPointBJ(=讀取單位(面向點)(
FlushGameCacheBJ(=刪除緩存(
FlushStoredMissionBJ(=刪除類別(
AddResourceAmountBJ(=增加儲金量(
BlightGoldMineForPlayerBJ(=創建不死族金礦(立即)(
WaygateActivateBJ(=啟用/禁用傳送門(
WaygateSetDestinationLocBJ(=設置傳送門目的點(
UnitSetUsesAltIconBJ(=開啟/關閉小地圖特殊標誌(
AddItemToStockBJ(=添加物品(指定市場)(
AddUnitToStockBJ(=添加單位(指定市場)(
RemoveItemFromStockBJ(=刪除物品(指定市場)(
RemoveUnitFromStockBJ(=刪除單位(指定市場)(
IsDestructableAliveBJ(=可破壞物存活(
IsDestructableDeadBJ(=可破壞物死亡(
IsDestructableInvulnerableBJ(=可破壞物無敵(
IsPointBlightedBJ(=坐標點被荒蕪地表覆蓋 [R](
IsTerrainPathableBJ(=地形通行狀態關閉(指定坐標) [R](
GetStoredBooleanBJ(=緩存讀取布爾值(
UnitHasItemOfTypeBJ(=持有物品(指定類型)(
IsItemHiddenBJ(=物品隱藏(
LeaderboardHasPlayerItemBJ(=玩家在排行榜(
WaygateIsActiveBJ(=傳送門激活(
IsPlayerFlagSetBJ(=玩家參數開啟(
IsTriggerQueuedBJ(=觸發在隊列中(
IsTriggerQueueEmptyBJ(=觸發隊列為空(
IsUnitAliveBJ(=單位存活(
IsUnitDeadBJ(=單位死亡(
IsUnitPausedBJ(=單位暫停(
IsUnitHiddenBJ(=單位隱藏(
IsUnitIllusionBJ(=單位是鏡像(
UnitCanSleepBJ(=允許夜晚睡眠(
UnitIsSleepingBJ(=正在睡眠(
IsUnitLoadedBJ(=被裝載(
IsUnitInTransportBJ(=被指定單位裝載(
UnitHasBuffBJ(=擁有魔法傚果(
IsUnitGroupEmptyBJ(=單位組為空(
IsUnitGroupInRectBJ(=單位組中單位在矩形區域內(
IsUnitGroupDeadBJ(=單位組中所有單位死亡(
GetTerrainCliffLevelBJ(=地形懸崖高度(指定坐標) [R](
GetTerrainVarianceBJ(=地形樣式(指定坐標) [R](
GetStoredIntegerBJ(=緩存讀取整數(
GetHeroStatBJ(=英雄屬性(
LeaderboardGetPlayerIndexBJ(=排行榜位置(
IMinBJ(=取較小值(
IMaxBJ(=取較大值(
IAbsBJ(=絕對值(
ISignBJ(=符號標誌(
GetPlayerTaxRateBJ(=玩家所得稅 [R](
CountPlayersInForceBJ(=玩家組中玩家數量(
UnitInventorySizeBJ(=物品欄格數(
UnitCountBuffsExBJ(=擁有Buff數量 [R](
QueuedTriggerCountBJ(=隊列中觸發數量(
GetLastTransmissionDurationBJ(=最後發言長度 [舊](
GetTimeOfDayScalePercentBJ(=晝夜時間流逝速度(
GetStoredRealBJ(=緩存讀取實數(
GetItemLifeBJ(=生命值(
GetLightningColorRBJ(=紅顏色值(
GetLightningColorGBJ(=綠顏色值(
GetLightningColorBBJ(=藍顏色值(
GetLightningColorABJ(=Alpha通道值(
GetRandomPercentageBJ(=隨機百分數(
RMinBJ(=取較小值(
RMaxBJ(=取較大值(
RAbsBJ(=絕對值(
RSignBJ(=符號標誌(
SinBJ(=正弦(弧度) [R](
CosBJ(=餘弦(弧度) [R](
TanBJ(=正切(弧度) [R](
AsinBJ(=反正弦(弧度) [R](
AcosBJ(=反餘弦(弧度) [R](
AtanBJ(=反正切(弧度) [R](
Atan2BJ(=反正切(Y:X)(弧度) [R](
GetPlayerHandicapXPBJ(=經驗增長率(
GetPlayerHandicapBJ(=生命障礙(
GetRectWidthBJ(=寬度(
GetRectHeightBJ(=高度(
GetSoundDurationBJ(=音效長度(
GetSoundFileDurationBJ(=音樂長度(
GetUnitPropWindowBJ(=當前轉向角度(弧度制) [R](
GetUnitDefaultPropWindowBJ(=默認轉向角度(
SubStringBJ(=截取字符串(
OrderId2StringBJ(=轉換命令ID為字符串(
UnitId2StringBJ(=轉換單位類型為字符串(
GetAbilityEffectBJ(=技能效果路徑名(
GetAbilitySoundBJ(=技能音效名(
GetStoredStringBJ(=讀取字符串(
PolarProjectionBJ(=極坐標位移點(
WaygateGetDestinationLocBJ(=傳送門目的地(
GetCurrentCameraBoundsMapRectBJ(=當前可用鏡頭範圍(
OffsetRectBJ(=位移創建矩形區域(
RectFromCenterSizeBJ(=新建矩形區域(指定中心點)(
GetLastRestoredUnitBJ(=最後讀取的單位 [舊](
GetLastReplacedUnitBJ(=最後替換的單位 [舊](
GetAttackedUnitBJ(=被攻擊單位(
GetKillingUnitBJ(=凶手單位(
GetLoadedUnitBJ(=被裝載單位(
GetTransportUnitBJ(=運輸單位(
ChooseRandomCreepBJ(=隨機中立生物類型(
ChooseRandomNPBuildingBJ(=隨機中立建築類型(
String2UnitIdBJ(=轉換字符串為單位類型(
String2OrderIdBJ(=轉換命令字符串為命令ID(
UnitId2OrderIdBJ(=轉換單位類型為命令ID(
GetIssuedOrderIdBJ(=發布的命令ID(
RandomDestructableInRectSimpleBJ(=矩形區域內的隨機可破壞物(
RandomDestructableInRectBJ(=矩形區域內的隨機可破壞物(指定條件)(
RandomItemInRectSimpleBJ(=矩形區域內隨機物品(
RandomItemInRectBJ(=矩形區域內隨機物品(指定條件)(
UnitItemInSlotBJ(=單位持有物品(
GetItemOfTypeFromUnitBJ(=單位持有物品(指定類型)(
ChooseRandomItemExBJ(=隨機物品類型(指定分類)(
ChooseRandomItemBJ(=隨機物品類型(
GetLearnedSkillBJ(=學習技能 [R](
LeaderboardGetIndexedPlayerBJ(=所在位置玩家(
GetLastCreatedEffectBJ(=最後創建的特效 [舊](
GetLastCreatedLightningBJ(=最後創建的閃電效果 [舊](
GetTerrainTypeBJ(=指定坐標地形 [R](
GetLastCreatedQuestBJ(=最後創建的任務 [舊](
GetLastCreatedQuestItemBJ(=最後創建的任務項目 [舊](
GetLastCreatedDefeatConditionBJ(=最後創建的失敗條件 [舊](
GetClickedDialogBJ(=點擊的對話框(
GetLastCreatedButtonBJ(=最後創建的對話框按鈕 [舊](
GetClickedButtonBJ(=點擊的對話框按鈕(
PlayerGetLeaderboardBJ(=玩家使用的排行榜(
CreateTimerBJ(=新建計時器 [R](
GetLastCreatedTimerBJ(=最後啟用的計時器 [舊](
GetLastCreatedTimerDialogBJ(=最後創建的計時器窗口 [舊](
GetLastCreatedGameCacheBJ(=最後創建的遊戲緩存 [舊](
TriggerRegisterGameStateEventTimeOfDay(=遊戲時間改變(
TriggerRegisterVariableEvent(=實數變化(
TriggerRegisterGameEvent(=比賽事件(
TriggerRegisterTimerEventSingle(=遊戲逝去時間(
TriggerRegisterTimerEventPeriodic(=時間週期事件(
TriggerRegisterTimerEvent(=遊戲流失時間 [新](
TriggerRegisterTimerExpireEvent(=計時器到期(
TriggerRegisterDialogEvent(=對話框點擊(
TriggerRegisterDialogButtonEvent(=對話框按鈕被點擊 [R](
TriggerRegisterTrackableHitEvent(=鼠標點擊可追蹤對象 [R](
TriggerRegisterTrackableTrackEvent(=鼠標移動到追蹤對象 [R](
TriggerRegisterPlayerChatEvent(=聊天信息(
TriggerRegisterPlayerEventEndCinematic(=按下Esc鍵(
TriggerRegisterPlayerStateEvent(=屬性變化(
TriggerRegisterPlayerEventAllianceChanged(=聯盟狀態更改(
TriggerRegisterPlayerAllianceChange(=聯盟狀態更改(指定項目)(
TriggerRegisterPlayerEventVictory(=勝利(
TriggerRegisterPlayerEventDefeat(=失敗(
TriggerRegisterPlayerEventLeave(=離開遊戲(
TriggerRegisterDeathEvent(=可破壞物死亡(
TriggerRegisterDestDeathInRegionEvent(=可破壞物在區域內死亡(矩形區域)(
TriggerRegisterUnitEvent(=指定單位事件(
TriggerRegisterPlayerUnitEventSimple(=玩家單位事件(
TriggerRegisterPlayerUnitEvent(=玩家單位事件(滿足條件) [新](
TriggerRegisterEnterRectSimple(=單位進入矩形區域(
TriggerRegisterLeaveRectSimple(=單位離開矩形區域(
TriggerRegisterEnterRegionSimple(=單位進入不規則區域 [R](
TriggerRegisterLeaveRegionSimple(=單位離開不規則區域 [R](
TriggerRegisterEnterRegion(=單位進入不規則區域(指定條件) [R](
TriggerRegisterLeaveRegion(=單位離開不規則區域(指定條件) [R](
TriggerRegisterUnitInRangeSimple(=接近指定單位(
TriggerRegisterUnitLifeEvent(=生命值變化(
TriggerRegisterUnitManaEvent(=魔法值變化(
GetBooleanAnd(=條件A與條件B(
GetBooleanOr(=條件A或條件B(
DoNothing(=無動作(
CommentString(=注釋(
ExecuteFunc(=運行函數 [R](
TriggerSleepAction(=等待(
PolledWait(=等待(遊戲時間)(
SetForLoopIndexA(=設置循環整數A [R](
SetForLoopIndexB(=設置循環整數B [R](
StartMeleeAI(=啟用對戰AI(
StartCampaignAI(=啟用戰役AI(
CommandAI(=發送AI命令(
PauseCompAI(=暫停/恢復AI腳本運行 [R](
RemoveGuardPosition(=忽視單位警戒點(
RemoveAllGuardPositions(=忽視所有單位警戒點(
RecycleGuardPosition(=恢復單位警戒點(
SetUnitCreepGuard(=鎖定單位警戒點 [R](
LockGuardPosition(=鎖定單位警戒點(
DisableTrigger(=關閉(
EnableTrigger(=開啟(
ConditionalTriggerExecute(=初始化運行觸發(檢查條件)(
TriggerExecute(=運行觸發(檢查條件)(
DestroyTrigger(=刪除觸發器 [R](
CreateNUnitsAtLoc(=創建單位(面向角度)(
CreateUnit(=創建單位(指定坐標) [新](
CreateUnitAtLoc(=創建單位(指定點) [新](
CreateUnitAtLocByName(=命令ID創建單位(指定點) [新](
CreateUnitByName(=命令ID創建單位(指定坐標) [新](
CreateCorpse(=創建屍體 [新](
CreateBlightedGoldmine(=創建不死族金礦 [新](
KillUnit(=殺死(
RemoveUnit(=刪除(
ShowUnit(=顯示/隱藏 [R](
ShowUnitHide(=隱藏(
ShowUnitShow(=顯示(
SetUnitColor(=改變隊伍顏色(
SetUnitOwner(=改變所屬(
UnitShareVision(=共享視野 [R](
SetUnitPositionLoc(=移動單位(立即)(指定點)(
SetUnitPosition(=移動單位(立即)(指定坐標) [R](
SetUnitX(=設置單位X坐標 [R](
SetUnitY(=設置單位Y坐標 [R](
SetUnitRallyPoint(=設置集結點(指定點)(
SetUnitRallyUnit(=設置集結點(指定單位)(
SetUnitRallyDestructable(=設置集結點(指定可破壞物)(
SetUnitState(=設置單位生命/魔法值 [R](
SetUnitInvulnerable(=設置無敵/可攻擊(
PauseUnit(=暫停/恢復 [R](
UnitPauseTimedLife(=暫停/恢復生命週期 [R](
UnitApplyTimedLife(=設置生命週期 [R](
SetUnitExploded(=設置死亡方式(
UnitSuspendDecay(=暫停屍體腐爛 [R](
UnitResetCooldown(=重置技能CD(
UnitSetConstructionProgress(=設置建築建造進度條(
UnitSetUpgradeProgress(=設置建築升級進度條(
UnitAddSleepPerm(=控制單位睡眠狀態(
UnitWakeUp(=叫醒單位(
UnitGenerateAlarms(=設置警報開啟/關閉(
SetUnitRescuable(=設置可否營救(對玩家) [R](
SetUnitRescueRange(=設置營救範圍(
SetUnitUseFood(=允許/禁止人口占用 [R](
SetUnitFacingTimed(=設置單位面向角度(指定時間)(
SetUnitFacing(=設置單位面向角度(立即) [R](
SetUnitFacingToFaceUnitTimed(=設置單位面向單位(
SetUnitFacingToFaceLocTimed(=設置單位面向點(
SetUnitMoveSpeed(=設置移動速度(
SetUnitPathing(=設置碰撞開關(
SetUnitAcquireRange(=設置主動攻擊範圍(
SetUnitUserData(=設置自定義值(
UnitRemoveBuffsEx(=刪除魔法傚果(詳細類別) [R](
UnitRemoveBuffs(=刪除魔法傚果(指定極性) [R](
UnitAddAbility(=添加技能 [R](
UnitRemoveAbility(=刪除技能 [R](
UnitMakeAbilityPermanent(=設置技能永久性 [R](
UnitAddType(=添加類別 [R](
UnitRemoveType(=刪除類別 [R](
DecUnitAbilityLevelSwapped(=降低技能等級(
DecUnitAbilityLevel(=降低技能等級 [R](
IncUnitAbilityLevelSwapped(=提升技能等級(
IncUnitAbilityLevel(=提升技能等級 [R](
SetUnitAbilityLevelSwapped(=設置技能等級(
SetUnitAbilityLevel(=設置技能等級 [R](
IssueImmediateOrder(=發布命令(無目標)(
IssuePointOrderLoc(=發布命令(指定點)(
IssuePointOrder(=發布命令(指定坐標) [R](
IssueTargetOrder(=發布命令(指定單位)(
IssueTargetDestructableOrder(=發布命令(指定可破壞物)(
IssueTargetItemOrder(=發布命令(指定物品)(
IssueImmediateOrderById(=按ID發布命令(無目標) [R](
IssuePointOrderById(=按ID發布命令(指定坐標) [R](
IssuePointOrderByIdLoc(=按ID發布命令(指定點) [R](
IssueTargetOrderById(=按ID發布命令(指定單位) [R](
IssueBuildOrderById(=發布建造命令(指定坐標) [R](
UnitDropItemPointLoc(=發布丟棄物品命令(指定點)(
UnitDropItemPoint(=發布丟棄物品命令(指定坐標) [R](
UnitDropItemSlot(=移動物品到物品欄 [R](
UnitDropItemTarget(=發布給予物品命令(
IssueNeutralImmediateOrder(=發布中介命令(無目標) [R](
IssueNeutralPointOrder(=發布中介命令(指定坐標) [R](
IssueNeutralTargetOrder(=發布中介命令(指定單位) [R](
IssueNeutralImmediateOrderById(=按ID發布中介命令(無目標) [R](
IssueNeutralPointOrderById(=按ID發布中介命令(指定坐標) [R](
IssueNeutralTargetOrderById(=按ID發布中介命令(指定單位) [R](
UnitDamagePointLoc(=傷害區域 [舊](
UnitDamagePoint(=傷害區域 [R](
UnitDamageTarget(=傷害目標 [R](
UnitPoolAddUnitType(=添加單位類型 [R](
UnitPoolRemoveUnitType(=刪除單位類型 [R](
PlaceRandomUnit(=選擇放置單位 [R](
DestroyUnitPool(=刪除單位池 [R](
ForGroup(=選取單位組內單位做動作(
GroupAddUnitSimple(=添加單位(
GroupAddUnit(=添加單位 [R](
GroupAddGroup(=添加單位組(
GroupEnumUnitsOfType(=為單位組添加單位(單位命令ID) [新](
GroupEnumUnitsOfPlayer(=為單位組添加單位(指定玩家) [新](
GroupEnumUnitsOfTypeCounted(=為單位組添加單位(單位命令ID)(指定數量) [新](
GroupEnumUnitsInRectCounted(=為單位組添加單位(指定區域)(指定數量) [新](
GroupEnumUnitsInRect(=為單位組添加單位(指定區域) [新](
GroupEnumUnitsInRangeOfLocCounted(=為單位組添加單位(指定範圍)(點)(指定數量) [新](
GroupEnumUnitsInRangeOfLoc(=為單位組添加單位(指定範圍)(點) [新](
GroupEnumUnitsInRange(=為單位組添加單位(指定範圍)(坐標) [新](
GroupEnumUnitsInRangeCounted(=為單位組添加單位(指定範圍)(坐標)(指定數量) [新](
GroupRemoveUnitSimple(=移除單位(
GroupRemoveUnit(=移除單位 [R](
GroupRemoveGroup(=移除單位組(
GroupClear(=清空單位組(
DestroyGroup(=刪除單位組 [R](
GroupImmediateOrder(=發布命令(無目標)(
GroupPointOrderLoc(=發布命令(指定點)(
GroupPointOrder(=發布命令(指定坐標) [R](
GroupTargetOrder(=發布命令(指定單位)(
GroupTargetDestructableOrder(=發布命令(指定可破壞物)(
GroupTargetItemOrder(=發布命令(指定物品)(
GroupImmediateOrderById(=按ID發布命令(無目標) [R](
GroupPointOrderById(=按ID發布命令(指定坐標) [R](
GroupPointOrderByIdLoc(=按ID發布命令(指定點) [R](
GroupTargetOrderById(=按ID發布命令(指定單位) [R](
CreateUbersplat(=創建(
DestroyUbersplat(=刪除(
ResetUbersplat(=重置(
FinishUbersplat(=結束(
ShowUbersplat(=顯示/隱藏 [R](
SetUbersplatRenderAlways(=設置永久渲染狀態(
SetUbersplatRender(=設置渲染狀態(
MoveLocation(=移動點 [R](
RemoveLocation(=清除點 [R](
ForceCinematicSubtitles(=字幕顯示(
DisplayCineFilter(=顯示/隱藏濾鏡(
PingMinimapLocForForce(=小地圖信號(指定玩家組)(
PingMinimap(=小地圖信號(所有玩家) [R](
PingMinimapEx(=小地圖信號(指定顏色)(所有玩家) [R](
PingMinimapLocForForceEx(=小地圖信號(指定顏色)(指定玩家組)(
UnitAddIndicator(=閃動指示器(對單位) [R](
ShowInterfaceForceOff(=信箱模式開啟(指定玩家組)(
ShowInterfaceForceOn(=信箱模式開啟關閉(指定玩家組)(
ShowInterface(=開啟/關閉信箱模式(所有玩家) [R](
EnableUserControl(=啟用/禁用玩家控制權(所有玩家) [R](
SetUserControlForceOff(=禁用玩家控制權(指定玩家組)(
SetUserControlForceOn(=啟用玩家控制權(指定玩家組)(
EnableOcclusion(=允許/禁止閉塞(所有玩家) [R](
EnableWorldFogBoundary(=允許/禁止邊界染色(所有玩家) [R](
SetUnitAnimationByIndex(=指定序號播放單位動畫 [R](
SetUnitAnimationWithRarity(=播放單位動畫(指定概率)(
SetUnitAnimation(=播放單位動畫(
QueueUnitAnimation(=將單位動畫加入隊列(
ResetUnitAnimation(=重置單位動畫(
AddUnitAnimationProperties(=添加/刪除單位動畫附加名 [R](
SetUnitLookAt(=鎖定身體朝向(
ResetUnitLookAt(=重置身體朝向(
SetUnitScalePercent(=改變單位尺寸(
SetUnitScale(=改變單位尺寸 [R](
SetUnitVertexColor(=改變單位顏色 [R](
SetUnitTimeScalePercent(=改變單位動畫播放速度(
SetUnitTimeScale(=改變單位動畫播放速度 [R](
SetUnitTurnSpeed(=改變單位轉身速度(
SetUnitBlendTime(=改變單位混合時間(
SetUnitFlyHeight(=改變單位飛行高度(
SetUnitPropWindow(=改變單位轉向角度(弧度制) [R](
SetDestructableAnimation(=播放可破壞物動畫(
QueueDestructableAnimation(=將可破壞物動畫加入隊列(
SetDestructableAnimationSpeed(=改變可破壞物動畫播放速度 [R](
SetDestAnimationSpeedPercent(=改變可破壞物動畫播放速度(
SetDoodadAnimationRect(=播放矩形區域內地形裝飾物動畫 [R](
SetDoodadAnimation(=播放圓範圍內地形裝飾物動畫 [R](
DialogDisplay(=顯示/隱藏 [R](
DialogSetMessage(=設置標題(
DialogAddButton(=添加對話框按鈕(
DialogAddQuitButton(=添加退出遊戲按鈕 [R](
DialogClear(=清空對話框(
DialogDestroy(=刪除對話框 [R](
MeleeStartingVisibility(=使用對戰晝夜設置(
MeleeStartingHeroLimit(=英雄限制(
MeleeGrantHeroItems(=英雄初始物品(
MeleeStartingResources(=設置初始資源(
MeleeClearExcessUnits(=刪除多餘單位(
MeleeStartingUnits(=創建初始單位(
MeleeStartingAI(=運行AI(
MeleeInitVictoryDefeat(=強制勝利/失敗條件(
MeleeStartingUnitsForPlayer(=創建初始單位(指定玩家)(
CreateMultiboard(=創建(
DestroyMultiboard(=刪除(
MultiboardDisplay(=顯示/隱藏 [R](
MultiboardSuppressDisplay(=顯示/隱藏多面板模式 [R](
MultiboardMinimize(=最大/最小化 [R](
MultiboardClear(=清空多面板(
MultiboardSetTitleTextColor(=設置標題顏色 [R](
MultiboardSetTitleText(=設置標題(
MultiboardSetRowCount(=設置行數(
MultiboardSetColumnCount(=設置列數(
MultiboardSetItemStyle(=設置指定項目顯示風格 [R](
MultiboardSetItemValue(=設置指定項目文本 [R](
MultiboardSetItemValueColor(=設置指定項目顏色 [R](
MultiboardSetItemWidth(=設置指定項目寬度 [R](
MultiboardSetItemIcon(=設置指定項目圖標 [R](
MultiboardSetItemsStyle(=設置所有項目顯示風格 [R](
MultiboardSetItemsValue(=設置所有項目文本 [R](
MultiboardSetItemsValueColor(=設置所有項目顏色 [R](
MultiboardSetItemsWidth(=設置所有項目寬度 [R](
MultiboardSetItemsIcon(=設置所有項目圖標 [R](
MultiboardReleaseItem(=刪除多面板項目[R](
AddWeatherEffectSaveLast(=創建天氣效果(
EnableWeatherEffect(=啟用/禁用天氣效果(
RemoveWeatherEffect(=刪除天氣效果(
TerrainDeformStop(=停止地形變化 [R](
TerrainDeformStopAll(=停止所有地形變化(
SetWaterDeforms(=開啟/關閉水面變形(
SetTerrainType(=改變地形類型(指定坐標) [R](
SetTerrainPathable(=設置地形通行狀態(指定坐標) [R](
SetWaterBaseColor(=設置水顏色 [R](
SetSkyModel(=設置天空(
SetTerrainFogEx(=設置迷霧 [R](
ResetTerrainFog(=重置迷霧(
SetBlightRect(=創建/刪除荒蕪地表(矩形區域) [R](
SetBlightPoint(=創建/刪除荒蕪地表(指定坐標) [新](
SetBlight(=創建/刪除荒蕪地表(圓範圍)(指定坐標) [R](
SetBlightLoc(=創建/刪除荒蕪地表(圓範圍)(指定點) [新](
PauseTimer(=暫停計時器 [R](
ResumeTimer(=恢復暫停計時器 [R](
DestroyTimer(=刪除計時器 [R](
CreateTimerDialog(=創建計時器窗口(
DestroyTimerDialog(=刪除計時器窗口(
TimerDialogDisplay(=顯示/隱藏計時器窗口(所有玩家) [R](
TimerDialogSetTitle(=改變計時器窗口標題(
TimerDialogSetTitleColor(=改變計時器窗口文字顏色 [R](
TimerDialogSetTimeColor(=改變計時器窗口時間顏色 [R](
TimerDialogSetSpeed(=設置計時器窗口速率 [R](
TimerDialogSetRealTimeRemaining(=設置計時器窗口顯示的時間 [新](
CameraSetupApplyForceDuration(=應用鏡頭(所有玩家) [R](
CameraSetupApplyForPlayer(=應用鏡頭(指定玩家)(
PanCameraToTimed(=平移鏡頭(所有玩家) [R](
PanCameraToTimedLocForPlayer(=平移鏡頭(指定玩家)(
PanCameraTo(=平移鏡頭(所有玩家) [新](
PanCameraToTimedWithZ(=指定高度平移鏡頭(所有玩家) [R](
PanCameraToTimedLocWithZForPlayer(=指定高度平移鏡頭(指定玩家)(
SetCameraField(=設置鏡頭屬性(所有玩家) [R](
SetCameraFieldForPlayer(=設置鏡頭屬性(指定玩家)(
SetCameraRotateMode(=指定點旋轉鏡頭(所有玩家) [R](
SetCameraTargetController(=鎖定鏡頭到單位(所有玩家) [R](
SetCameraTargetControllerNoZForPlayer(=鎖定鏡頭到單位(指定玩家)(
SetCameraOrientController(=鎖定鏡頭到單位(固定鏡頭源)(所有玩家) [R](
SetCinematicCamera(=播放電影鏡頭(所有玩家) [R](
SetCinematicCameraForPlayer(=播放電影鏡頭(指定玩家)(
StopCamera(=停止播放鏡頭(所有玩家) [R](
ResetToGameCamera(=重置遊戲鏡頭(所有玩家) [R](
ResetToGameCameraForPlayer(=重置遊戲鏡頭(指定玩家)(
CameraSetSmoothingFactor(=設置鏡頭平滑參數(
CameraSetSourceNoiseEx(=搖晃鏡頭源(所有玩家) [R](
CameraSetSourceNoiseForPlayer(=搖晃鏡頭源(指定玩家)(
CameraSetTargetNoiseEx(=搖晃鏡頭目標(所有玩家) [R](
CameraSetTargetNoiseForPlayer(=搖晃鏡頭目標(指定玩家)(
CameraSetEQNoiseForPlayer(=震動鏡頭(指定玩家)(
CameraClearNoiseForPlayer(=停止搖晃/震動鏡頭(指定玩家)(
SetCameraBounds(=設置可用鏡頭區域(所有玩家) [R](
SetCameraQuickPosition(=設置空格鍵轉向點(所有玩家) [R](
SetCameraQuickPositionLocForPlayer(=設置空格鍵轉向點(指定玩家)(
FogEnable(=啟用/禁用戰爭迷霧 [R](
FogEnableOn(=啟用戰爭迷霧(
FogEnableOff(=禁用戰爭迷霧(
FogMaskEnable(=啟用/禁用黑色陰影 [R](
FogMaskEnableOn(=啟用黑色陰影(
FogMaskEnableOff(=禁用黑色陰影(
CreateFogModifierRect(=創建可見度修正器(矩形區域)(
CreateFogModifierRadiusLoc(=創建可見度修正器(圓範圍)(
FogModifierStart(=啟用可見度修正器(
FogModifierStop(=禁用可見度修正器(
DestroyFogModifier(=刪除可見度修正器(
SetFogStateRect(=設置地圖迷霧(矩形區域) [R](
SetFogStateRadius(=設置地圖迷霧(圓範圍) [R](
CreateDestructableLoc(=創建可破壞物(
KillDestructable(=殺死(
RemoveDestructable(=刪除(
DestructableRestoreLife(=復活(
ShowDestructable(=顯示/隱藏 [R](
SetDestructableLife(=設置生命值(指定值)(
SetDestructableMaxLife(=設置最大生命值(
ChangeElevatorWalls(=打開/關閉升降機墻壁(
ChangeElevatorHeight(=設置升降機高度(
SetDestructableInvulnerable(=設置無敵/可攻擊(
SetDestructableOccluderHeight(=設置閉塞高度(
EnumDestructablesInRectAll(=選取矩形區域內可破壞物做動作(
CreateLeaderboard(=創建(
DestroyLeaderboard(=刪除(
LeaderboardClear(=清空 [R](
LeaderboardDisplay(=顯示/隱藏 [R](
PlayerSetLeaderboard(=設置玩家使用的排行榜 [R](
LeaderboardSetLabel(=設置標題(
LeaderboardSetLabelColor(=設置文字顏色 [R](
LeaderboardSetValueColor(=設置數值顏色 [R](
LeaderboardSetStyle(=設置顯示樣式(
LeaderboardSetSizeByItemCount(=設置排行榜行數 [新](
LeaderboardRemoveItem(=刪除排行榜行數 [新](
LeaderboardAddItem(=添加玩家(
LeaderboardRemovePlayerItem(=移除玩家(
DestroyTextTag(=刪除(
SetTextTagVisibility(=顯示/隱藏(所有玩家) [R](
SetTextTagVelocity(=設置速率 [R](
SetTextTagColor(=改變顏色 [R](
SetTextTagPos(=改變位置(指定坐標) [R](
SetTextTagPosUnit(=改變位置(指定單位)(
SetTextTagText(=改變文字 [R](
SetTextTagSuspended(=暫停/恢復(
SetTextTagPermanent(=設置永久性(
SetTextTagLifespan(=設置生命週期(
SetTextTagFadepoint(=設置消逝時間點(
SetTextTagAge(=設置已存在時間(
RegionAddRect(=添加區域 [R](
RegionClearRect(=移除區域 [R](
RegionAddCell(=添加單元點(指定坐標) [R](
RegionAddCellAtLoc(=添加單元點(指定點) [R](
RegionClearCell(=移除單元點(指定坐標) [R](
RegionClearCellAtLoc(=移除單元點(指定點) [R](
RemoveRegion(=刪除不規則區域 [R](
SetRect(=設置矩形區域(指定坐標) [R](
SetRectFromLoc(=設置矩形區域(指定點) [R](
MoveRectTo(=移動矩形區域(指定坐標) [R](
MoveRectToLoc(=移動矩形區域(指定點)(
RemoveRect(=刪除矩形區域 [R](
CreateQuest(=創建任務(
DestroyQuest(=刪除任務(
QuestSetEnabled(=啟用/禁用任務 [R](
QuestSetCompleted(=設置任務完成(
QuestSetFailed(=設置任務失敗(
QuestSetDiscovered(=設置任務被發現(
QuestSetTitle(=設置任務標題(
QuestSetDescription(=設置任務說明(
QuestSetIconPath(=設置任務圖標 [新](
QuestSetRequired(=設置任務類型 [新](
QuestItemSetCompleted(=設置任務項目完成(
QuestItemSetDescription(=改變任務項目說明(
CreateDefeatCondition(=創建失敗條件(
DestroyDefeatCondition(=刪除失敗條件(
DefeatConditionSetDescription(=改變失敗條件說明(
FlashQuestDialogButton(=閃動任務按鈕(
AddLightningLoc(=創建(
AddLightning(=創建閃電效果(指定坐標) [新](
AddLightningEx(=創建閃電效果(指定坐標與高度) [新](
DestroyLightning(=刪除(
MoveLightning(=移動(指定坐標) [新](
MoveLightningEx(=移動(指定坐標) [R](
MoveLightningLoc(=移動(指定點)(
SetLightningColor(=改變顏色(
PlaySound(=播放音效(
StopSound(=停止音效(
KillSoundWhenDone(=刪除音效(
SetSoundVolume(=設置音效音量 [R](
SetSoundPlayPosition(=設置音效播放時間點 [R](
SetSoundDistanceCutoff(=設置聲音截斷距離(
SetSoundPitch(=設置聲音速率(
AttachSoundToUnit(=綁定單位(
SetSoundPosition(=設置3D音效位置(指定坐標) [R](
SetSoundDistances(=設置3D音效衰減範圍(
SetAmbientDaySound(=使用白天環境音效(
SetAmbientNightSound(=使用夜晚環境音效(
EnableDawnDusk(=允許/禁止晝夜交替音效(
SetMapMusic(=設置背景音樂列表 [R](
ClearMapMusic(=清空背景音樂列表(
PlayMusic(=播放背景音樂(
PlayMusicEx(=跳播背景音樂(
StopMusic(=停止背景音樂(
ResumeMusic(=恢復背景音樂(
SetMusicVolume(=設置背景音樂音量 [R](
SetMusicPlayPosition(=設置背景音樂播放時間點 [R](
PlayThematicMusic(=播放主題音樂(
PlayThematicMusicEx(=跳播主題音樂 [R](
EndThematicMusic(=停止主題音樂(
SetThematicMusicPlayPosition(=設置主題音樂播放時間點 [R](
VolumeGroupSetVolume(=設置多通道音量 [R](
VolumeGroupReset(=重置多通道音量(
AddSpecialEffectLoc(=創建特效(指定點)(
DestroyEffect(=刪除特效(
AddSpellEffectById(=技能效果(指定坐標) [新](
AddSpellEffectByIdLoc(=技能效果(指定點) [新](
AddSpellEffectTargetById(=技能效果(綁定單位) [新](
AddSpellEffect(=命令ID技能特效(指定坐標) [新](
AddSpellEffectLoc(=命令ID技能特效(指定點) [新](
AddSpellEffectTarget(=命令ID技能特效(綁定單位) [新](
CreateImage(=創建(
DestroyImage(=刪除(
ShowImage(=顯示/隱藏 [R](
SetImageConstantHeight(=設置高度(
SetImagePosition(=改變位置(指定坐標) [R](
SetImageColor(=改變顏色 [R](
SetImageRender(=設置渲染狀態(
SetImageRenderAlways(=設置永久渲染狀態(
SetImageAboveWater(=水面顯示狀態(
SetImageType(=改變類型(
SetPlayerState(=設置屬性(
SetPlayerTaxRate(=設置所得稅 [R](
SetPlayerAlliance(=設置聯盟狀態(指定項目) [R](
SetPlayerAbilityAvailable(=允許/禁用技能 [R](
SetPlayerMaxHeroesAllowed(=限制英雄數量(
SetPlayerTechResearchedSwap(=設置科技等級(
SetPlayerTechMaxAllowedSwap(=設置最大科技等級(
SetPlayerColor(=改變玩家顏色 [R](
SetPlayerHandicap(=設置生命障礙 [R](
SetPlayerOnScoreScreen(=顯示/隱藏計分屏顯示 [R](
SetPlayerName(=更改名字(
RemovePlayer(=刪除玩家 [新](
DefineStartLocation(=設置玩家初始點位置(指定坐標) [新](
DefineStartLocationLoc(=設置玩家初始點位置(指定點) [新](
SetPlayerTeam(=設置玩家隊伍數值 [新](
SetPlayerController(=設置玩家用戶(
SetPlayerStartLocation(=設置玩家開始點tion(
ForceAddPlayerSimple(=添加玩家(
ForceAddPlayer(=添加玩家 [R](
ForceEnumPlayers(=為玩家組添加玩家 [新](
ForceEnumPlayersCounted(=為玩家組添加玩家(指定數量) [新](
ForceEnumAllies(=為玩家組添加玩家(指定玩家條件) [新](
ForceRemovePlayerSimple(=移除玩家(
ForceRemovePlayer(=移除玩家 [R](
ForceClear(=清空玩家組(
DestroyForce(=刪除玩家組 [R](
UnitDropItem(=創建物品 [新](
CreateItemLoc(=創建(
SetItemVisible(=顯示/隱藏 [R](
SetItemPosition(=移動到坐標(立即)(指定坐標) [R](
SetItemPositionLoc(=移動到指定點(立即)(指定點)(
SetItemCharges(=設置使用次數(
SetItemInvulnerable(=設置無敵/可攻擊(
SetItemPawnable(=設置可否抵押(
SetItemDroppable(=設置可否丟棄(
SetItemDropOnDeath(=設置死亡是否掉落(
SetItemPlayer(=改變所屬玩家(
SetItemUserData(=設置自定義值(
EnumItemsInRect(=選取矩形區域內物品做動作(
ItemPoolAddItemType(=添加物品類型 [R](
ItemPoolRemoveItemType(=刪除物品類型 [R](
PlaceRandomItem(=選擇放置物品 [R](
DestroyItemPool(=刪除物品池 [R](
ClearSelectionForPlayer(=清空選擇(指定玩家)(
SelectUnitForPlayerSingle(=選擇單位(指定玩家)(
SelectUnitAddForPlayer(=添加選擇單位(指定玩家)(
SelectUnitRemoveForPlayer(=取消選擇單位(指定玩家)(
ClearSelection(=清空選擇(所有玩家)(
SelectUnitSingle(=選擇單位(所有玩家)(
SelectUnitAdd(=添加選擇單位(所有玩家)(
SelectUnitRemove(=取消選擇單位(所有玩家)(
SelectHeroSkill(=學習技能(
UnitStripHeroLevel(=降低等級 [R](
SetHeroLevel(=設置等級(
SetHeroXP(=設置經驗值(
AddHeroXP(=增加經驗值 [R](
AddHeroXPSwapped(=增加經驗值(
SuspendHeroXP(=允許/禁止經驗獲取 [R](
SetPlayerHandicapXP(=設置經驗獲得率 [R](
ReviveHero(=立即復活(指定坐標) [R](
ReviveHeroLoc(=立即復活(指定點)(
SetHeroStr(=設置英雄力量 [R](
SetHeroAgi(=設置英雄敏捷 [R](
SetHeroInt(=設置英雄智力 [R](
ModifyHeroStat(=修改英雄屬性(
UnitModifySkillPoints(=添加剩餘技能點 [R](
ModifyHeroSkillPoints(=修改剩餘技能點(
SetReservedLocalHeroButtons(=保留英雄圖標(
UnitAddItem(=給予物品 [R](
UnitAddItemSwapped(=給予物品(
UnitAddItemByIdSwapped(=創建物品給英雄(
UnitAddItemToSlotById(=新建物品到指定物品欄 [R](
UnitRemoveItemSwapped(=丟棄物品(指定物品)(
UnitRemoveItemFromSlotSwapped(=丟棄物品(指定物品欄)(
UnitUseItem(=使用物品(無目標)(
UnitUseItemPoint(=使用物品(指定坐標)(
UnitUseItemPointLoc(=使用物品(指定點)(
UnitUseItemTarget(=使用物品(對單位)(
UnitUseItemDestructable(=使用物品(對可破壞物)(
DisplayTextToPlayer(=對玩家顯示文本消息(自動限時) [R](
DisplayTimedTextToPlayer(=對玩家顯示文本消息(指定時間) [R](
DisplayTextToForce(=對玩家組顯示文本消息(自動限時)(
DisplayTimedTextToForce(=對玩家組顯示文本消息(指定時間)(
ClearTextMessages(=清空文本信息(所有玩家) [R](
PauseGame(=暫停/恢復遊戲 [R](
PauseGameOn(=暫停遊戲(
PauseGameOff(=恢復遊戲(
SetGameSpeed(=設置遊戲速度(
SetMapFlag(=設置地圖參數(
SetGameDifficulty(=設置遊戲難度 [R](
SetTimeOfDay(=設置遊戲時間(
SetTimeOfDayScale(=設置晝夜時間流逝速度 [R](
DoNotSaveReplay(=關閉遊戲錄像功能 [R](
Cheat(=輸入作弊碼 [R](
ShareEverythingWithTeam(=對盟友共享視野和完全控制權(
MakeUnitsPassiveForPlayer(=改變所有單位為中立受害單位(
ChangeLevel(=切換關卡 [R](
SaveGame(=保存進度 [R](
LoadGame(=讀取進度(
RenameSaveDirectory(=重命名存檔文件夾(
RemoveSaveDirectory(=刪除存檔文件夾(
CopySaveGame(=複製存檔文件(
SetCampaignMenuRace(=設置戰役背景(
SetMissionAvailable(=允許/禁止關卡(
SetCampaignAvailable(=允許/禁止戰役(
ShowCustomCampaignButton(=顯示/隱藏自定義戰役按鈕(
SetAllyColorFilterState(=設置聯盟顏色顯示(
SetCreepCampFilterState(=設置小地圖中立生物顯示(
EnableMinimapFilterButtons(=允許/禁用小地圖按鈕(
EnableSelect(=允許/禁用選擇(
EnableDragSelect(=允許/禁用框選(
EnablePreSelect(=允許/禁用預選(
ForceUIKey(=按下UI鍵(
ForceUICancel(=按下Esc鍵(
Preload(=預載文件(
PreloadEnd(=開始預載(
Preloader(=批量預載(
EndGame(=結束遊戲 [新](
RestartGame(=重新開始遊戲 [新](
ReloadGame(=重新載入遊戲 [新](
DisplayLoadDialog(=顯示裝載載遊戲對話框 [新](
DisableRestartMission(=禁止/允許重新開始遊戲 [新](
SetTeams(=設置隊伍數量 [新](
SetPlayers(=設置玩家數量 [新](
InitGameCache(=創建緩存(
SaveGameCache(=本地保存遊戲緩存(
StoreUnit(=記錄單位(
StoreReal(=記錄實數(
StoreInteger(=記錄整數(
StoreBoolean(=記錄布爾值(
StoreString(=記錄字符串(
ReloadGameCachesFromDisk(=讀取本地緩存數據(
FlushGameCache(=刪除緩存(
FlushStoredMission(=刪除類別(
AddResourceAmount(=增加儲金量(
SetResourceAmount(=設置儲金量(
BlightGoldMineForPlayer(=創建不死族金礦(立即)(
WaygateActivate(=啟用/禁用傳送門(
WaygateSetDestination(=設置傳送門目的坐標 [R](
SetAltMinimapIcon(=設置小地圖特殊標誌(
UnitSetUsesAltIcon(=開啟/關閉小地圖特殊標誌(
AddItemToStock(=添加物品(指定市場)(
AddItemToAllStock(=添加物品(所有市場)(
AddUnitToStock(=添加單位(指定市場)(
AddUnitToAllStock(=添加單位(所有市場)(
RemoveItemFromStock(=刪除物品(指定市場)(
RemoveItemFromAllStock(=刪除物品(所有市場)(
RemoveUnitFromStock(=刪除單位(指定市場)(
RemoveUnitFromAllStock(=刪除單位(所有市場)(
RemoveItem(=刪除物品(
SetItemTypeSlots(=限制物品種類(指定市場)(
SetAllItemTypeSlots(=限制物品種類(所有市場)(
SetUnitTypeSlots(=限制單位種類(指定市場)(
SetAllUnitTypeSlots(=限制單位種類(所有市場)(
SetGameTypeSupported(=設置遊戲類型支持 [新](
SetResourceDensity(=設置資源密度 [新](
SetCreatureDensity(=設置生物密度 [新](
ResetTrigger(=重置觸發 [新](
IsDestructableInvulnerable(=可破壞物無敵(
IsPointBlighted(=坐標點被荒蕪地表覆蓋 [R](
IsTerrainPathable(=地形通行狀態關閉(指定坐標) [R](
IsMapFlagSet(=地圖參數設置(
IsCustomCampaignButtonVisibile(=自定義戰役按鈕可見(
GetCreepCampFilterState(=小地圖中立生物顯示開啟(
SaveGameExists(=遊戲存檔存在(
IsNoVictoryCheat(=無法勝利 [R](
IsNoDefeatCheat(=無法失敗 [R](
GetStoredBoolean(=緩存讀取布爾值(
HaveStoredValue(=緩存項存在(
IsSuspendedXP(=經驗不可獲得(
CheckItemStatus(=物品狀態檢查(
CheckItemcodeStatus(=物品類型狀態檢查(
IsItemVisible(=物品可見 [R](
IsItemOwned(=物品被持有(
IsItemPowerup(=物品是拾取時自動使用的 [R](
IsItemSellable(=物品可被市場隨機出售 [R](
IsItemPawnable(=物品可被抵押 [R](
RectContainsItem(=物品在矩形區域(
IsItemInvulnerable(=物品無敵(
LeaderboardHasPlayerItem(=玩家在排行榜(
IsLeaderboardDisplayed(=排行榜是顯示的 [新](
IsMultiboardDisplayed(=多面板顯示(
IsMultiboardMinimized(=多面板最小化(
WaygateIsActive(=傳送門激活(
IsGameTypeSupported(=遊戲類型是支持的 [新](
IsPlayerAlly(=是玩家的盟友(
IsPlayerEnemy(=是玩家的敵人(
GetPlayerAlliance(=聯盟狀態設置(
IsPlayerInForce(=在玩家組(
IsPlayerObserver(=觀看者 [新](
IsTimerDialogDisplayed(=計時器窗口是顯示的 [新](
IsQuestItemCompleted(=任務項目完成(
IsQuestEnabled(=任務激活(
IsQuestCompleted(=任務完成(
IsQuestFailed(=任務失敗(
IsQuestDiscovered(=任務被發現(
IsQuestRequired(=是主要任務(
RectContainsLoc(=包含點(
IsPointInRegion(=包含坐標(
IsLocationInRegion(=包含點(
IsTriggerEnabled(=觸發開啟(
TriggerEvaluate(=觸發條件成立(
IsUnitType(=單位類別檢查(
IsUnitIdType(=單位類別檢查(指定單位類型)(
IsUnitInGroup(=在單位組(
IsUnitInForce(=在玩家組 [新](
RectContainsUnit(=在矩形區域內(
IsUnitInRegion(=在不規則區域內 [R](
IsUnitPaused(=單位暫停(
IsUnitHidden(=單位隱藏(
IsUnitRace(=單位種族 [新](
IsUnitIllusion(=單位是鏡像(
IsHeroUnitId(=單位類型是英雄 [新](
UnitHasBuffsEx(=單位指定魔法傚果 [新](
UnitCanSleepPerm(=允許控制睡眠狀態(
UnitCanSleep(=允許夜晚睡眠(
UnitIsSleeping(=正在睡眠(
DoesUnitGenerateAlarms(=開啟警報(
IsUnitLoaded(=被裝載(
IsUnitInTransport(=被指定單位裝載(
IsUnitSelected(=被玩家選擇(
IsUnitDetected(=被玩家探測 [新](
IsUnitInRange(=單位與單位間距離 [新](
IsUnitInRangeXY(=單位與坐標間距離 [新](
IsUnitInRangeLoc(=單位與點間距離 [新](
IsUnitAlly(=是玩家的同盟單位(
IsUnitEnemy(=是玩家的敵對單位(
IsUnitOwnedByPlayer(=是玩家的 [新](
IsFogEnabled(=戰爭迷霧開啟(
IsFogMaskEnabled(=黑色陰影開啟(
IsUnitVisible(=單位可見(
IsUnitInvisible(=單位不可見(
IsUnitFogged(=單位在迷霧中(
IsUnitMasked(=單位在黑色陰影中(
IsLocationVisibleToPlayer(=點可見(
IsLocationFoggedToPlayer(=點在迷霧中(
IsLocationMaskedToPlayer(=點在黑色陰影中(
IsVisibleToPlayer(=坐標可見 [新](
IsFoggedToPlayer(=坐標在戰爭迷霧中 [新](
IsMaskedToPlayer(=坐標在黑色陰影中 [新](
IsCineFilterDisplayed(=濾鏡是否開啟 [新](
GetForLoopIndexA(=循環整數A [舊](
GetForLoopIndexB(=循環整數B [舊](
StringLength(=字符串長度(
R2I(=轉換實數為整數(
S2I(=轉換字符串為整數(
GetElevatorHeight(=升降機高度(
GetTerrainCliffLevel(=地形懸崖高度(指定坐標) [R](
GetTerrainVariance(=地形樣式(指定坐標) [R](
GetLearnedSkillLevel(=學習技能等級(
GetPlayers(=玩家數量(
GetTeams(=隊伍數量 [廢棄](
GetAllyColorFilterState(=聯盟顏色顯示設置(
GetTournamentFinishNowRule(=比賽結束規則(
GetTournamentScore(=對戰比賽得分(
GetStoredInteger(=緩存讀取整數(
GetHeroLevel(=英雄等級(
GetHeroXP(=英雄經驗值(
GetHeroStr(=英雄力量 [R](
GetHeroAgi(=英雄敏捷 [R](
GetHeroInt(=英雄智力 [R](
GetHeroSkillPoints(=未分配技能點數(
GetItemLevel(=物品等級(
GetItemCharges(=使用次數(
GetItemUserData(=物品自定義值(
LeaderboardGetPlayerIndex(=排行榜位置(
GetRandomInt(=隨機整數(
ModuloInteger(=模(
MultiboardGetRowCount(=行數(
MultiboardGetColumnCount(=列數(
GetResourceAmount(=儲金量(
GetPlayerState(=玩家屬性(
GetPlayerTaxRate(=玩家所得稅 [R](
GetPlayerScore(=玩家得分(
GetConvertedPlayerId(=玩家索引(
GetPlayerId(=玩家ID號 [新](
GetPlayerTypedUnitCount(=玩家單位數量(命令ID) [新](
GetPlayerStructureCount(=建築數量(
GetPlayerUnitCount(=非建築單位數量(
GetPlayerTechCountSimple(=當前科技等級(
GetPlayerTechMaxAllowedSwap(=最大科技等級(
GetPlayerTeam(=玩家隊伍數值 [新](
GetPlayerStartLocation(=玩家自定義值 [新](
CountUnitsInGroup(=單位組中單位數量(
CountLivingPlayerUnitsOfTypeId(=玩家擁有單位數量(
GetUnitFoodUsed(=單位使用人口數量(
GetUnitFoodMade(=單位提供人口數量(
GetFoodUsed(=單位使用人口數量(指定單位類型)(
GetFoodMade(=單位提供人口數量(指定單位類型)(
GetUnitPointValue(=單位附加值(
GetUnitPointValueByType(=單位附加值(指定單位類型)(
GetUnitUserData(=單位自定義值(
GetUnitLevel(=單位等級(
GetUnitAbilityLevel(=單位技能等級 [R](
GetUnitAbilityLevelSwapped(=單位技能等級(
UnitInventoryCount(=持有物品數量(
UnitInventorySize(=物品欄格數(
UnitCountBuffsEx(=擁有Buff數量 [R](
GetTriggerEvalCount(=觸發條件判斷次數(
GetTriggerExecCount(=觸發動作運行次數(
GetLocationX(=點的X軸坐標(
GetLocationY(=點的Y軸坐標(
GetLocationZ(=點的Z軸高度 [R](
CameraSetupGetField(=鏡頭屬性(指定鏡頭) [R](
CameraSetupGetFieldSwap(=鏡頭屬性(指定鏡頭)(
GetCameraField(=鏡頭屬性(當前鏡頭)(
GetCameraTargetPositionX(=當前鏡頭目標X坐標(
GetCameraTargetPositionY(=當前鏡頭目標Y坐標(
GetCameraTargetPositionZ(=當前鏡頭目標Z坐標(
GetCameraEyePositionX(=當前鏡頭源X坐標(
GetCameraEyePositionY(=當前鏡頭源Y坐標(
GetCameraEyePositionZ(=當前鏡頭源Z坐標(
CameraSetupGetDestPositionX(=鏡頭X坐標 [新](
CameraSetupGetDestPositionY(=鏡頭Y坐標 [新](
GetCameraBoundMinX(=當前可用鏡頭區域最小X坐標 [新](
GetCameraBoundMinY(=當前可用鏡頭區域最小Y坐標 [新](
GetCameraBoundMaxX(=當前可用鏡頭區域最大X坐標 [新](
GetCameraBoundMaxY(=當前可用鏡頭區域最大Y坐標 [新](
GetLastTransmissionDuration(=最後發言長度 [舊](
*I2R(=轉換整數為實數(
S2R(=轉換字符串為實數(
Deg2Rad(=轉換角度為弧度(
Rad2Deg(=轉換弧度為角度(
TimerGetElapsed(=逝去時間(
TimerGetRemaining(=剩餘時間(
TimerGetTimeout(=設置時間(
GetDestructableLife(=生命值(
GetDestructableMaxLife(=最大生命值(
GetDestructableOccluderHeight(=閉塞高度(
GetDestructableX(=可破壞物所在X軸坐標 [R](
GetDestructableY(=可破壞物所在Y軸坐標 [R](
GetEventDamage(=傷害值(
GetOrderPointX(=命令發布點X坐標 [R](
GetOrderPointY(=命令發布點Y坐標 [R](
GetTournamentFinishSoonTimeRemaining(=比賽剩餘時間(
GetTimeOfDay(=遊戲時間(
GetStoredReal(=緩存讀取實數(
GetItemX(=物品的X軸坐標 [R](
GetItemY(=物品的Y軸坐標 [R](
GetLightningColorR(=紅顏色值(
GetLightningColorG(=綠顏色值(
GetLightningColorB(=藍顏色值(
GetLightningColorA(=Alpha通道值(
GetRandomReal(=隨機實數(
GetRandomDirectionDeg(=隨機角度(
DistanceBetweenPoints(=兩點間距離(
AngleBetweenPoints(=兩點間方向(
ModuloReal(=模(
Pow(=冪運算(
SquareRoot(=平方根(
Sin(=正弦(弧度) [R](
Cos(=餘弦(弧度) [R](
Tan(=正切(弧度) [R](
Asin(=反正弦(弧度) [R](
Acos(=反餘弦(弧度) [R](
Atan(=反正切(弧度) [R](
Atan2(=反正切(Y:X)(弧度) [R](
GetPlayerHandicapXP(=經驗增長率(
GetPlayerHandicap(=生命障礙(
GetPlayerStartLocationX(=玩家初始點X軸坐標 [新](
GetPlayerStartLocationY(=玩家初始點Y軸坐標 [新](
GetStartLocationX(=玩家初始點X軸坐標(整數) [新](
GetStartLocationY(=玩家初始點Y軸坐標(整數) [新](
GetRectCenterX(=中心X坐標(
GetRectCenterY(=中心Y坐標(
GetRectMinX(=左下角X坐標(
GetRectMinY(=左下角Y坐標(
GetRectMaxX(=右上角X坐標(
GetRectMaxY(=右上角Y坐標(
GetSoundDuration(=音效長度(
GetSoundFileDuration(=音樂長度(
GetUnitState(=屬性 [R](
GetUnitStateSwap(=屬性(
GetUnitLifePercent(=生命百分比(
GetUnitManaPercent(=魔法百分比(
GetUnitX(=單位所在X軸坐標 [R](
GetUnitY(=單位所在Y軸坐標 [R](
WaygateGetDestinationX(=傳誦門傳誦點X軸坐標 [新](
WaygateGetDestinationY(=傳誦門傳誦點Y軸坐標 [新](
GetUnitFacing(=面向角度(
GetUnitMoveSpeed(=當前移動速度(
GetUnitDefaultMoveSpeed(=默認移動速度(
GetUnitAcquireRange(=當前主動攻擊範圍(
GetUnitDefaultAcquireRange(=默認主動攻擊範圍(
GetUnitTurnSpeed(=當前轉身速度(
GetUnitDefaultTurnSpeed(=默認轉身速度(
GetUnitPropWindow(=當前轉向角度(弧度制) [R](
GetUnitDefaultPropWindow(=默認轉向角度(
GetUnitFlyHeight(=當前飛行高度(
GetUnitDefaultFlyHeight(=默認飛行高度(
SubString(=截取字符串(
OrderId2String(=轉換命令ID為字符串(
UnitId2String(=轉換單位類型為字符串(
GetLocalizedString(=本地字符串 [R](
StringIdentity(=本地字符串(
StringCase(=大小寫轉換(
GetDestructableName(=可破壞物名字(
GetEventPlayerChatString(=輸入的聊天信息(
GetEventPlayerChatStringMatched(=匹配的聊天信息(
GetSaveBasicFilename(=存檔文件名(
GetAbilityName(=技能名稱(
GetAbilityEffect(=技能效果路徑名(
GetAbilitySound(=技能音效名(
GetStoredString(=讀取字符串(
GetHeroProperName(=英雄稱謂(
GetItemName(=物品名字(
MultiboardGetTitleText(=多面板標題(
LeaderboardGetLabelText(=排行板標題 [新](
GetPlayerName(=玩家名字(
GetUnitName(=單位名字(
GetRectCenter(=矩形區域中心(
GetRandomLocInRect(=矩形區域內隨機點(
OffsetLocation(=坐標位移點(
CameraSetupGetDestPositionLoc(=鏡頭目標點(
GetCameraTargetPositionLoc(=當前鏡頭目標點(
GetCameraEyePositionLoc(=當前鏡頭源位置(
GetDestructableLoc(=可破壞物位置(
GetOrderPointLoc(=命令發布點(
GetSpellTargetLoc(=技能施放點(
GetItemLoc(=物品位置(
GetPlayerStartLocationLoc(=玩家開始位置(
GetStartLocationLoc(=玩家開始位置 [新](
GetUnitLoc(=單位位置(
GetUnitRallyPoint(=單位集結點(
CreateRegion(=新建不規則區域 [新](
GetTriggeringRegion(=觸發區域 [R](
GetCameraBoundsMapRect(=初始可用鏡頭範圍(
GetPlayableMapRect(=可用地圖區域 [舊](
GetEntireMapRect(=完整地圖區域(
GetWorldBounds(=地圖最大區域 [新](
bj_lastCreatedUnit(=最後創建的單位 [R](
GetLastCreatedUnit(=最後創建的單位 [舊](
GetLastHauntedGoldMine(=最後創建的不死族金礦 [舊](
GetEnumUnit(=選取單位(
GetFilterUnit(=匹配單位(
FirstOfGroup(=單位組中第一個單位(
GroupPickRandomUnit(=單位組中隨機單位(
GetAttacker(=攻擊單位(
GetBuyingUnit(=購買者(
GetCancelledStructure(=被取消的建築(
GetSpellAbilityUnit(=施法單位(
GetConstructedStructure(=完成的建築(
GetConstructingStructure(=正在建造的建築(
GetEventDamageSource(=傷害來源(
GetDecayingUnit(=腐化的單位(
GetDyingUnit(=死亡單位(
GetEnteringUnit(=進入的單位(
GetManipulatingUnit(=操作物品的單位(
GetKillingUnit(=凶手單位(
GetLearningUnit(=學習技能的英雄(
GetLeavingUnit(=離開的單位(
GetLevelingUnit(=升級的英雄(
GetLoadedUnit(=被裝載單位(
GetOrderedUnit(=發布命令的單位(
GetChangingUnit(=被改變所有者的單位(
GetResearchingUnit(=研究科技的單位(
GetRevivableUnit(=可復活英雄(
GetRevivingUnit(=復活英雄(
GetSellingUnit(=販賣者(
GetSoldUnit(=被販賣單位(
GetSummonedUnit(=召喚單位(
GetSummoningUnit(=召喚者(
GetOrderTargetUnit(=命令發布目標(
GetSpellTargetUnit(=技能施放目標(
GetEventTargetUnit(=事件目標單位(
GetTrainedUnit(=訓練單位(
GetTransportUnit(=運輸單位(
GetTriggerUnit(=觸發單位(
GetUnitRallyUnit(=單位集結點目標(
CreateUnitPool(=新建單位池 [R](
GetUnitTypeId(=指定單位的類型(
ChooseRandomCreep(=隨機中立生物類型(
ChooseRandomNPBuilding(=隨機中立建築類型(
GetTrainedUnitType(=訓練單位類型(
GetIssuedOrderId(=發布的命令ID(
GetUnitCurrentOrder(=當前命令ID(
GetLastCreatedDestructable(=最後創建的可破壞物 [舊](
CreateDestructableZ(=新建可破壞物(
CreateDeadDestructableZ(=新建可破壞物(死亡的) [R](
GetEnumDestructable(=選取的可破壞物(
GetFilterDestructable(=匹配的可破壞物(
GetDyingDestructable(=死亡的可破壞物(
GetOrderTargetDestructable(=命令發布目標(可破壞物)(
GetSpellTargetDestructable(=技能施放目標(可破壞物)(
GetUnitRallyDestructable(=單位集結點目標(
GetDestructableTypeId(=指定可破壞物的類型(
CreateItem(=新建物品 [R](
GetLastCreatedItem(=最後創建的物品 [舊](
GetLastRemovedItem(=最後丟棄的物品 [舊](
GetEnumItem(=選取物品(
GetFilterItem(=匹配物品(
UnitItemInSlot(=單位持有物品(
GetManipulatedItem(=被操作物品(
GetSoldItem(=被售出物品(
GetOrderTargetItem(=命令發布目標(
GetSpellTargetItem(=技能施放目標(
GetItemType(=指定物品的分類(
GetItemTypeId(=指定物品的類型(
ChooseRandomItemEx(=隨機物品類型(指定分類)(
ChooseRandomItem(=隨機物品類型(
CreateItemPool(=新建物品池 [R](
GetResearched(=被研究科技(
GetSpellAbilityId(=施放技能(
GetLearnedSkill(=學習技能 [R](
GetEnumPlayer(=選取玩家(
GetFilterPlayer(=匹配玩家(
GetOwningPlayer(=單位所有者(
GetItemPlayer(=物品所屬玩家(
ForcePickRandomPlayer(=玩家組中隨機玩家(
GetLocalPlayer(=本地玩家 [R](
ConvertedPlayer(=轉換玩家索引號為玩家(
GetChangingUnitPrevOwner(=原所有者(
GetTriggerPlayer(=觸發玩家(
CreateGroup(=新建的單位組 [R](
GetLastCreatedGroup(=最後創建的單位組 [舊](
GetRandomSubGroup(=單位組中隨機單位(
GetUnitsInRectAll(=矩形區域內的單位(
GetUnitsInRectOfPlayer(=矩形區域內的玩家單位(
GetUnitsInRectMatching(=矩形區域內的單位(指定條件)(
GetUnitsInRangeOfLocAll(=圓範圍內單位(
GetUnitsInRangeOfLocMatching(=圓範圍內單位(指定條件)(
GetUnitsOfPlayerAll(=玩家單位(
GetUnitsOfPlayerAndTypeId(=玩家單位(指定單位類型)(
GetUnitsOfPlayerMatching(=玩家單位(指定條件)(
GetUnitsOfTypeIdAll(=所有指定類型單位(
GetUnitsSelectedAll(=玩家選擇單位(
CreateForce(=新建玩家組 [R](
GetPlayersAll(=所有玩家 [舊](
GetPlayersByMapControl(=所有指定控制者的玩家(
GetPlayersMatching(=所有符合條件的玩家(
GetPlayersAllies(=玩家的盟友(
GetPlayersEnemies(=玩家的敵人(
GetForceOfPlayer(=轉換玩家為玩家組(
GetPlayerRace(=玩家種族(
GetUnitRace(=單位種族(
GetCurrentCameraSetup(=玩家當前鏡頭(
CreateFogModifierRadius(=新建可見度修正器(圓範圍) [R](
GetLastCreatedFogModifier(=最後創建的可見度修正器 [舊](
GetTriggeringTrigger(=當前觸發(
CreateTrigger(=新建觸發 [新](
GetGameDifficulty(=當前遊戲難度(
GetAIDifficulty(=玩家的AI難度(
GetGameSpeed(=當前遊戲速度(
GetPlayerController(=玩家控制者(
GetPlayerColor(=玩家顏色(
GetPlayerSlotState(=玩家遊戲狀態(
AddSpecialEffect(=新建特效(指定坐標) [R](
AddSpecialEffectTarget(=新建特效(綁定單位) [R](
GetLastCreatedImage(=最後創建的圖像 [舊](
GetLastCreatedUbersplat(=最後創建的地面紋理變化 [舊](
AddWeatherEffect(=新建天氣效果 [R](
GetLastCreatedWeatherEffect(=最後創建的天氣效果 [舊](
TerrainDeformCrater(=新建地形變化:彈坑 [R](
TerrainDeformRipple(=新建地形變化:波紋 [R](
TerrainDeformWave(=新建地形變化:衝擊波 [R](
TerrainDeformRandom(=新建地形變化:隨機 [R](
GetLastCreatedTerrainDeformation(=最後創建的地形變化 [舊](
GetTerrainType(=指定坐標地形 [R](
GetLastPlayedSound(=最後播放的音效 [舊](
GetLastPlayedMusic(=最後播放的音樂 [舊](
GetClickedDialog(=點擊的對話框(
GetClickedButton(=點擊的對話框按鈕(
GetLastCreatedLeaderboard(=最後創建的排行榜 [舊](
PlayerGetLeaderboard(=玩家使用的排行榜(
GetLastCreatedMultiboard(=最後創建的多面板 [舊](
MultiboardGetItem(=多面板項目 [R](
CreateTimer(=新建計時器 [R](
GetExpiredTimer(=到期的計時器(
CreateTrackable(=新建可追蹤對象 [R](
GetTriggeringTrackable(=事件響應 - 觸發對象 [R](
CreateTextTag(=新建漂浮文字 [R](
GetLastCreatedTextTag(=最後創建的漂浮文字 [舊](
TownThreatened(=基地被攻擊(
TownHasMine(=基地有金礦(
TownHasHall(=基地有主建築(
CaptainIsHome(=攻擊指揮官在家(
CaptainIsFull(=攻擊組準備完畢(
CaptainIsEmpty(=攻擊組為空(
CaptainRetreating(=攻擊指揮官撤退(
CaptainAtGoal(=攻擊指揮官到達目的地(
CaptainInCombat(=指揮官在戰鬥(
CreepsOnMap(=存在中立生物(
GetUnitCount(=單位總數(
GetUnitCountDone(=已完成單位總數(
GetTownUnitCount(=單位總數(指定基地)(
GetMinesOwned(=擁有金礦數量(
GetGoldOwned(=未被使用的金礦數量(
TownWithMine(=有金礦的基地ID(
UnitHasItem(=持有物品(
GetGold(=當前黃金資源(
GetWood(=當前木材資源(
GetUnitGoldCost(=單位造價(黃金)(
GetUnitWoodCost(=單位造價(木材)(
GetUnitBuildTime(=單位建造時間(
GetUpgradeLevel(=當前科技等級(
GetUpgradeGoldCost(=科技升級花費黃金(
GetUpgradeWoodCost(=科技升級花費木材(
GetNextExpansion(=下一個擴張點ID(
CommandsWaiting(=等待命令數量(
CaptainGroupSize(=攻擊組人數(
CaptainReadinessHP(=攻擊組生命級別(
CaptainReadinessMa(=攻擊魔法級別(
TriggerAddAction(=添加觸發器動作(
TriggerAddCondition(=添加觸發器限制條件(
SetMapName(=地圖名字(
SetMapDescription(=地圖介紹(
SetPlayerRacePreference(=設置玩家種族(
SetPlayerRaceSelectable(=設置玩家種族可選(
SetWidgetLife(=設置有生命對象的生命(
DialogCreate(=新建對話框(
SetStartLocPrioCount(=設置開始點優先權數量(
SetStartLocPrio(=設置開始點優先權(
Player(=玩家(
